<?php
declare(strict_types=1);

use Dormitory\Domain\DailyPaymentService;
use Dormitory\Domain\PaymentEvidenceRegistry;
use Dormitory\Domain\PaymentService;
use Dormitory\Http\HttpException;
use Dormitory\Security\Password;

// This executable is restricted to a fresh disposable schema. All provider I/O is injected.
if(PHP_SAPI!=='cli'||getenv('APP_ENV')!=='testing'||!preg_match('/^appj_[a-z0-9_]+$/D',(string)getenv('DB_DATABASE')))exit(64);
$app=require dirname(__DIR__).'/bootstrap.php';$pdo=$app->database()->pdo();
if(($argv[1]??'')==='refund-race'){
    try{$pdo->beginTransaction();$q=$pdo->prepare("INSERT INTO daily_refunds(booking_id,payment_id,amount,purpose,request_key,reference_no,reason,recorded_by) VALUES(?,?,'60.00','cancellation',?,?,?,?)");$q->execute([(int)$argv[2],(int)$argv[3],$argv[5],'RACE-BANK-'.$argv[5],'Actual race fixture refund',(int)$argv[4]]);usleep(200000);$pdo->commit();$result=['saved'=>true];}
    catch(PDOException $e){if($pdo->inTransaction())$pdo->rollBack();$result=['saved'=>false,'driver_code'=>(int)($e->errorInfo[1]??0)];}
    echo json_encode($result,JSON_THROW_ON_ERROR);exit;
}
foreach(['admin_users','rooms','daily_bookings','daily_payments','payments','daily_refunds']as$table)if((int)$pdo->query('SELECT COUNT(*) FROM '.$table)->fetchColumn()!==0)throw new RuntimeException('Fresh disposable fixture required');
$passed=0;$assert=static function(bool $ok,string $why='Assertion failed'):void{if(!$ok)throw new RuntimeException($why);};
$test=static function(string $name,callable $fn)use(&$passed):void{$fn();$passed++;echo "PASS {$name}\n";};
$expect=static function(callable $fn,string $code)use($assert):void{try{$fn();}catch(HttpException $e){$assert($e->errorCode===$code,'Expected '.$code.' got '.$e->errorCode);return;}throw new RuntimeException('Expected '.$code);};
$q=$pdo->prepare("INSERT INTO admin_users(username,password_hash,role,auth_version,active) VALUES('daily_payment_owner',?,'owner',1,1)");$q->execute([Password::hash('Disposable-Daily-Payment-Fixture-2026!')]);$owner=(int)$pdo->lastInsertId();
$app->settings()->update(['promptpay_target'=>'0812345678','promptpay_name'=>'Fixture','slip_provider'=>'slipok','slipok_branch_id'=>'fixture','slipok_api_key'=>'fixture-not-real','payment_receiver_account_tail'=>'567890'],$owner);
$app->billing()->updateSettings(['water_rate'=>'0','electric_rate'=>'0','due_days'=>7],$owner);
$today=(new DateTimeImmutable('today',new DateTimeZone('Asia/Bangkok')))->format('Y-m-d');$tomorrow=(new DateTimeImmutable($today))->modify('+1 day')->format('Y-m-d');$sequence=0;$images=[];$imageSequence=0;
$make=function(string $deposit='50.00')use($app,$today,$tomorrow,&$sequence):array{
    $sequence++;$room=$app->rooms()->create(['room_code'=>'DP-'.$sequence,'floor'=>1,'room_type'=>'Fixture','rental_mode'=>'daily','daily_rate'=>'100.00','daily_deposit'=>$deposit,'max_guests'=>2]);
    $input=['room_id'=>$room['id'],'check_in_date'=>$today,'check_out_date'=>$tomorrow,'guests'=>1];$quote=$app->dailyBookings()->quote($input);
    return $app->dailyBookings()->createPublic($input+['quote_token'=>$quote['quote_token'],'full_name'=>'Daily fixture '.$sequence,'phone'=>'0878'.str_pad((string)$sequence,6,'0',STR_PAD_LEFT),'idempotency_key'=>'daily-payment-create-'.$sequence]);
};
$image=function()use($app,&$images,&$imageSequence):array{$path=tempnam($app->config->root.'/storage','daily-payment-fixture-');$images[]=$path;$im=imagecreatetruecolor(16,16);$imageSequence++;imagefill($im,0,0,imagecolorallocate($im,0,($imageSequence>>8)&255,$imageSequence&255));imagepng($im,$path);unset($im);return ['error'=>UPLOAD_ERR_OK,'tmp_name'=>$path,'size'=>filesize($path)];};
$mode='verified';$calls=0;$onRequest=null;$reference=null;$forcedAmount=null;
$transport=static function($url,$headers,$body)use(&$mode,&$calls,&$onRequest,&$reference,&$forcedAmount):array{
    $calls++;if($onRequest!==null)$onRequest();if($mode==='timeout')throw new RuntimeException('Fixture timeout');
    return ['_status'=>200,'success'=>true,'data'=>['success'=>true,'transRef'=>$reference??'DAILY-FIXTURE-'.$calls,'amount'=>$forcedAmount??($mode==='wrong_amount'?'1.00':$body['amount']),'transTimestamp'=>gmdate('Y-m-d\TH:i:s\Z'),'countryCode'=>'TH','paidLocalCurrency'=>'THB','receiver'=>['account'=>['value'=>'xxx567890']]]];
};
$service=new DailyPaymentService($app,$transport);$monthlyService=new PaymentService($app,$transport);
$key=static fn(string $prefix,int $id):string=>$prefix.'-fixture-idempotency-'.$id;
$expiredFixture=function(string $rate,string $adjustment,string $label,int $ageDays=8)use($app,$pdo,$today,$tomorrow,$key):array{
    $room=$app->rooms()->create(['room_code'=>'DP-'.$label,'floor'=>1,'room_type'=>'Fixture','rental_mode'=>'daily','daily_rate'=>$rate,'daily_deposit'=>'0.00','max_guests'=>2]);$token=hash('sha256',$label);
    $q=$pdo->prepare("INSERT INTO daily_bookings(reference_no,room_id,full_name,phone_norm,check_in_date,check_out_date,guests,nightly_rate,room_amount,deposit_amount,total_amount,status,expires_at,access_token_hash,idempotency_key,request_hash,created_at) VALUES(?,?,'Quarantine fixture','0899999910',?,?,1,?,?,'0.00',?,'pending',DATE_SUB(UTC_TIMESTAMP(6),INTERVAL ? DAY),?,?,?,DATE_SUB(UTC_TIMESTAMP(6),INTERVAL ? DAY))");$q->execute(['DY-'.$label,$room['id'],$today,$tomorrow,$rate,$rate,$rate,$ageDays,hash('sha256',$token),$key('quarantine-create',$room['id']),hash('sha256',$label.'-request'),$ageDays+1]);$id=(int)$pdo->lastInsertId();
    $pdo->prepare('INSERT INTO daily_booking_nights(booking_id,room_id,stay_date,nightly_rate) VALUES(?,?,?,?)')->execute([$id,$room['id'],$today,$rate]);$amount=Dormitory\Support\Validator::decimalString(Dormitory\Support\Validator::scaledDecimal($rate,'fixture_rate')+Dormitory\Support\Validator::scaledDecimal($adjustment,'fixture_adjustment'));
    $pdo->prepare("INSERT INTO payment_amount_registry(subject_type,subject_id,transfer_amount,created_at) VALUES('daily',?,?,DATE_SUB(UTC_TIMESTAMP(6),INTERVAL ? DAY))")->execute([$id,$amount,$ageDays+1]);$pdo->prepare("INSERT INTO daily_transfer_instructions(booking_id,booking_amount,adjustment_amount,transfer_amount,promptpay_target,recipient_name,created_at) VALUES(?,?,?,?,'0812345678','Fixture',DATE_SUB(UTC_TIMESTAMP(6),INTERVAL ? DAY))")->execute([$id,$rate,$adjustment,$amount,$ageDays+1]);
    return ['id'=>$id,'room_id'=>$room['id'],'access_token'=>$token,'amount'=>$amount];
};
$rejectSql=static function(callable $fn,string $reason)use($assert):void{try{$fn();}catch(PDOException $e){$assert((int)($e->errorInfo[1]??0)===1644&&str_contains($e->getMessage(),$reason),'Unexpected SQL refusal');return;}throw new RuntimeException('Expected SQL rejection '.$reason);};
try{
    $test('guest capability scopes QR and payment status and never exposes private evidence',function()use($make,$service,$expect,$assert,$app,$owner):void{
        $b=$make();$expect(fn()=>$service->reserve($b['id'],str_repeat('0',64)),'DAILY_BOOKING_NOT_FOUND');
        $s=$service->status($b['id'],$b['access_token']);$assert(!$s['paid']&&$s['payment']===null&&!isset($s['access_token_hash']));
        $app->settings()->update(['slip_provider'=>'none'],$owner);$expect(fn()=>$service->reserve($b['id'],$b['access_token']),'SLIP_NOT_CONFIGURED');$assert(!$service->status($b['id'],$b['access_token'])['capabilities']['promptpay_ready']);$app->settings()->update(['slip_provider'=>'slipok'],$owner);
    });
    $test('full principal and immutable QR cents are separate and repeated QR reuses the same allocation',function()use($make,$service,$assert,$pdo,$app,$owner,$expect):void{
        $b=$make();$one=$service->reserve($b['id'],$b['access_token']);$two=$service->reserve($b['id'],$b['access_token']);$assert($one===$two&&$one['bill_amount']==='150.00'&&(float)$one['amount']>150&&(float)$one['amount']<151);
        $q=$pdo->prepare("SELECT transfer_amount FROM payment_amount_registry WHERE subject_type='daily' AND subject_id=?");$q->execute([$b['id']]);$assert($q->fetchColumn()===$one['amount']);
        $expect(fn()=>$app->settings()->update(['promptpay_target'=>'0812345679'],$owner),'PROMPTPAY_HAS_RESERVED_DAILY_BOOKINGS');
    });
    $test('verified money atomically confirms inventory and lost responses replay without provider credit',function()use($make,$service,$image,$assert,&$calls):void{
        $b=$make();$service->reserve($b['id'],$b['access_token']);$f=$image();$p=$service->upload($b['id'],$b['access_token'],$f);$assert($p['status']==='verified'&&$p['booking_status']==='confirmed'&&$p['amount']==='150.00');$before=$calls;$again=$service->upload($b['id'],$b['access_token'],$f);$assert($again['id']===$p['id']&&$again['idempotent_replay']&&$calls===$before);
        $s=$service->status($b['id'],$b['access_token']);$assert($s['paid']&&!isset($s['payment']['slip_path'])&&!isset($s['payment']['slip_hmac']));
    });
    $test('timeout preserves a single pending receipt and owner retry settles the original evidence',function()use($make,$service,$image,$pdo,$assert,&$mode):void{
        $b=$make();$service->reserve($b['id'],$b['access_token']);$mode='timeout';$p=$service->upload($b['id'],$b['access_token'],$image());$assert($p['status']==='pending'&&$p['booking_status']==='pending');$mode='verified';$p=$service->retry($p['id']);$assert($p['status']==='verified'&&$p['booking_status']==='confirmed');
    });
    $test('a provider outage uses a durable daily retry quota and evidence can recover after cooldown',function()use($make,$service,$image,$pdo,$app,$assert,$expect,&$mode,&$calls):void{
        $b=$make();$service->reserve($b['id'],$b['access_token']);$mode='timeout';$p=$service->upload($b['id'],$b['access_token'],$image());for($i=0;$i<20;$i++)$service->retry($p['id']);$before=$calls;$expect(fn()=>$service->retry($p['id']),'RATE_LIMITED');$assert($calls===$before,'Quota denial reached provider');
        $bucket=hash_hmac('sha256','daily-payment-retry-evidence:'.$p['id'],$app->config->appKey());$q=$pdo->prepare('SELECT hits FROM rate_limits WHERE bucket_key=?');$q->execute([$bucket]);$assert((int)$q->fetchColumn()===20);
        $pdo->prepare('UPDATE rate_limits SET window_started_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 25 HOUR),blocked_until=NULL WHERE bucket_key=?')->execute([$bucket]);$mode='verified';$result=$service->retry($p['id']);$assert($result['status']==='verified'&&$result['booking_status']==='confirmed'&&$result['verification_attempts']>20,'Lifetime attempts must not make recovery impossible');
    });
    $test('late bank verification records verified money without resurrecting cancelled/rebooked inventory',function()use($make,$service,$image,$app,$owner,$today,$tomorrow,$key,$assert,&$onRequest):void{
        $b=$make();$service->reserve($b['id'],$b['access_token']);$replacement=null;
        $onRequest=function()use($app,$b,$owner,$today,$tomorrow,$key,&$replacement):void{$app->dailyBookings()->transition($b['id'],'cancel',['expected_version'=>1,'idempotency_key'=>$key('late-cancel',$b['id']),'reason'=>'Fixture cancelled during verification'],$owner);$input=['room_id'=>$b['room_id'],'check_in_date'=>$today,'check_out_date'=>$tomorrow,'guests'=>1];$q=$app->dailyBookings()->quote($input);$replacement=$app->dailyBookings()->createPublic($input+['quote_token'=>$q['quote_token'],'full_name'=>'Replacement fixture','phone'=>'0899999901','idempotency_key'=>$key('replacement',$b['id'])]);};
        $p=$service->upload($b['id'],$b['access_token'],$image());$onRequest=null;$assert($p['status']==='verified'&&$p['booking_status']==='cancelled'&&$p['refund_needed']);$assert($app->dailyBookings()->guestDetails($replacement['id'],$replacement['access_token'])['status']==='pending');
    });
    $test('expired holds release before rebooking while a late valid receipt remains refundable',function()use($app,$pdo,$today,$tomorrow,$service,$image,$assert,$key,&$onRequest):void{
        $room=$app->rooms()->create(['room_code'=>'DP-EXPIRED','floor'=>1,'room_type'=>'Fixture','rental_mode'=>'daily','daily_rate'=>'101.00','daily_deposit'=>'0.00','max_guests'=>2]);$token=str_repeat('a',64);
        $q=$pdo->prepare("INSERT INTO daily_bookings(reference_no,room_id,full_name,phone_norm,check_in_date,check_out_date,guests,nightly_rate,room_amount,deposit_amount,total_amount,status,expires_at,access_token_hash,idempotency_key,request_hash) VALUES('DY-EXPIRED-FIXTURE',?,'Expired fixture','0899999903',?,?,1,'101.00','101.00','0.00','101.00','pending',DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 1 SECOND),?,'expired-payment-fixture',?)");$q->execute([$room['id'],$today,$tomorrow,hash('sha256',$token),str_repeat('b',64)]);$id=(int)$pdo->lastInsertId();
        $q=$pdo->prepare("INSERT INTO daily_booking_nights(booking_id,room_id,stay_date,nightly_rate) VALUES(?,?,?,'101.00')");$q->execute([$id,$room['id'],$today]);
        $pdo->prepare("INSERT INTO payment_amount_registry(subject_type,subject_id,transfer_amount) VALUES('daily',?,'101.01')")->execute([$id]);$pdo->prepare("INSERT INTO daily_transfer_instructions(booking_id,booking_amount,adjustment_amount,transfer_amount,promptpay_target,recipient_name) VALUES(?,'101.00','0.01','101.01','0812345678','Fixture')")->execute([$id]);$replacement=null;
        $onRequest=function()use($app,$room,$today,$tomorrow,$key,$id,&$replacement):void{$input=['room_id'=>$room['id'],'check_in_date'=>$today,'check_out_date'=>$tomorrow,'guests'=>1];$quote=$app->dailyBookings()->quote($input);$replacement=$app->dailyBookings()->createPublic($input+['quote_token'=>$quote['quote_token'],'full_name'=>'Expiry replacement','phone'=>'0899999904','idempotency_key'=>$key('expired-replacement',$id)]);};
        $p=$service->upload($id,$token,$image());$onRequest=null;$assert($p['status']==='verified'&&$p['booking_status']==='expired'&&$p['refund_needed']);$assert($app->dailyBookings()->guestDetails($replacement['id'],$replacement['access_token'])['status']==='pending');$assert($service->statusForOwner($id)['received_amount']==='101.01');
    });
    $test('cash receipt is a distinct owner record, replay-safe and cannot coexist with a pending bank payment',function()use($make,$service,$owner,$key,$assert,$expect,$image,$pdo,&$mode):void{
        $b=$make();$input=['expected_version'=>1,'idempotency_key'=>$key('cash',$b['id']),'reference'=>'CASH-'.$b['id']];$p=$service->cash($b['id'],$input,$owner);$assert($p['method']==='cash'&&$p['status']==='verified'&&$p['transaction_ref']===null&&$p['transfer_amount']==='150.00');$assert($service->cash($b['id'],$input,$owner)['id']===$p['id']);
        $other=$make();$expect(fn()=>$service->cash($other['id'],['expected_version'=>1,'idempotency_key'=>$key('cash-ref-conflict',$other['id']),'reference'=>$input['reference']],$owner),'CASH_RECEIPT_REFERENCE_USED');$q=$pdo->prepare('SELECT COUNT(*) FROM daily_payments WHERE booking_id=?');$q->execute([$other['id']]);$assert((int)$q->fetchColumn()===0&&!$service->statusForOwner($other['id'])['paid']);
        $qr=$make();$service->reserve($qr['id'],$qr['access_token']);$expect(fn()=>$service->cash($qr['id'],['expected_version'=>1,'idempotency_key'=>$key('issued-qr-cash',$qr['id']),'reference'=>'ISSUED-'.$qr['id']],$owner),'DAILY_TRANSFER_ALREADY_ISSUED');
        $b=$make();$service->reserve($b['id'],$b['access_token']);$mode='timeout';$service->upload($b['id'],$b['access_token'],$image());$mode='verified';$expect(fn()=>$service->cash($b['id'],['expected_version'=>1,'idempotency_key'=>$key('blocked-cash',$b['id']),'reference'=>'BLOCKED-'.$b['id']],$owner),'PAYMENT_ALREADY_PENDING');
    });
    $test('checkout requires all security deposit returned or explicitly retained with an immutable reason',function()use($make,$service,$owner,$key,$app,$pdo,$assert,$expect):void{
        $b=$make();$service->cash($b['id'],['expected_version'=>1,'idempotency_key'=>$key('deposit-cash',$b['id']),'reference'=>'DEP-CASH-'.$b['id']],$owner);$app->dailyBookings()->transition($b['id'],'check-in',['expected_version'=>2,'idempotency_key'=>$key('check-in',$b['id'])],$owner);
        $expect(fn()=>$service->assertCheckoutReady($pdo,$b['id']),'DAILY_DEPOSIT_UNSETTLED');$service->settleDeposit($b['id'],['expected_version'=>3,'idempotency_key'=>$key('retain',$b['id']),'retained_amount'=>'10.00','reason'=>'Fixture damage receipt'],$owner);
        $refund=['expected_version'=>3,'idempotency_key'=>$key('deposit-refund',$b['id']),'amount'=>'10.00','reference'=>'BANK-REFUND-'.$b['id'],'reason'=>'Actual fixture outbound refund'];$one=$service->refund($b['id'],$refund,$owner);$two=$service->refund($b['id'],$refund,$owner);$assert($one['id']===$two['id']);
        $duplicate=$refund;$duplicate['idempotency_key']=$key('changed-refund-key',$b['id']);$duplicate['amount']='1.00';$expect(fn()=>$service->refund($b['id'],$duplicate,$owner),'REFUND_REFERENCE_USED');$q=$pdo->prepare('SELECT refunded_amount,deposit_refunded_amount FROM daily_payments WHERE booking_id=? AND status=\'verified\'');$q->execute([$b['id']]);$balances=$q->fetch();$assert($balances['refunded_amount']==='10.00'&&$balances['deposit_refunded_amount']==='10.00','Duplicate reference must roll back trigger counters');
        $final=$refund;$final['idempotency_key']=$key('final-deposit-refund',$b['id']);$final['amount']='30.00';$final['reference']='BANK-FINAL-REFUND-'.$b['id'];$service->refund($b['id'],$final,$owner);$service->assertCheckoutReady($pdo,$b['id']);
        $expect(fn()=>$service->refund($b['id'],['expected_version'=>3,'idempotency_key'=>$key('over-refund',$b['id']),'amount'=>'0.01','reference'=>'OVER-'.$b['id'],'reason'=>'Fixture over refund'],$owner),'REFUND_EXCEEDS_RECEIVED');
    });
    $test('bank references and canonical slip evidence cannot credit monthly and daily subjects twice',function()use($make,$service,$monthlyService,$app,$owner,$today,$image,$pdo,$assert,$expect,$key,&$reference):void{
        $room=$app->rooms()->create(['room_code'=>'MONTHLY-CROSS','floor'=>1,'room_type'=>'Fixture','monthly_rent'=>'150.00']);$period=substr($today,0,7);$resident=$app->bookings()->createAdminResident($owner,['room_id'=>$room['id'],'full_name'=>'Monthly fixture','phone'=>'0899999902','move_in_date'=>$period.'-01','opening_water_reading'=>'0','opening_electric_reading'=>'0','idempotency_key'=>'monthly-cross-module-fixture']);$app->meters()->record(['room_id'=>$room['id'],'period'=>$period,'water_current'=>'0','electric_current'=>'0'],$owner);$input=['period'=>$period,'room_ids'=>[$room['id']],'confirm_current_period'=>true];$preview=$app->billing()->preview($input);$bill=$app->billing()->bulk($input+['preview_token'=>$preview['preview_token']],$owner)['created'][0];$monthlyQr=$app->transfers()->reserve($bill['id'],$resident['resident_id']);
        $b=$make();$dailyQr=$service->reserve($b['id'],$b['access_token']);$assert($dailyQr['amount']!==$monthlyQr['transfer_amount']);$f=$image();$reference='CROSS-MODULE-BANK-REF';$monthly=$monthlyService->upload($bill['id'],$resident['resident_id'],$f);$assert($monthly['status']==='verified');$expect(fn()=>$service->upload($b['id'],$b['access_token'],$f),'DUPLICATE_SLIP');$daily=$service->upload($b['id'],$b['access_token'],$image());$assert($daily['status']==='rejected'&&!$service->statusForOwner($b['id'])['paid']);$reference=null;
    });
    $test('concurrent refunds cannot exceed the receipt even when two writers bypass service prechecks',function()use($make,$service,$owner,$key,$app,$pdo,$assert):void{
        $b=$make('0.00');$payment=$service->cash($b['id'],['expected_version'=>1,'idempotency_key'=>$key('race-cash',$b['id']),'reference'=>'RACE-CASH-'.$b['id']],$owner);$app->dailyBookings()->transition($b['id'],'cancel',['expected_version'=>2,'idempotency_key'=>$key('race-cancel',$b['id']),'reason'=>'Fixture cancellation refund race'],$owner);
        $command=[PHP_BINARY];$ini=php_ini_loaded_file();if(is_string($ini)&&$ini!==''){$command[]='-c';$command[]=$ini;}$command[]='-d';$command[]='extension_dir='.ini_get('extension_dir');
        // Preserve extensions explicitly enabled by the disposable runner's -d flags.
        foreach(['openssl','pdo_mysql','gd','mbstring','curl','fileinfo']as$extension)if(extension_loaded($extension)){$command[]='-d';$command[]='extension='.$extension;}
        $processes=[];for($i=0;$i<2;$i++){$p=proc_open(array_merge($command,[__FILE__,'refund-race',(string)$b['id'],(string)$payment['id'],(string)$owner,$key('parallel-refund-'.$i,$b['id'])]),[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__));if(!is_resource($p))throw new RuntimeException('Cannot spawn refund race fixture');fclose($pipes[0]);$processes[]=[$p,$pipes];}
        $results=[];foreach($processes as[$p,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$assert(proc_close($p)===0,$err);$results[]=json_decode($out,true,512,JSON_THROW_ON_ERROR);}
        $assert(count(array_filter($results,static fn(array $r):bool=>$r['saved']))===1,'Both concurrent refunds were accepted');$q=$pdo->prepare('SELECT refunded_amount FROM daily_payments WHERE id=?');$q->execute([$payment['id']]);$assert($q->fetchColumn()==='60.00');$q=$pdo->prepare('SELECT COUNT(*) FROM daily_refunds WHERE booking_id=?');$q->execute([$b['id']]);$assert((int)$q->fetchColumn()===1);
    });
    $test('expired QR allocations reuse after seven days while old and new capability claims stay separate',function()use($expiredFixture,$app,$pdo,$today,$tomorrow,$key,$service,$image,$assert,$rejectSql,&$reference):void{
        $old=$expiredFixture('7777.00','0.42','REUSE');
        // Occupy the other 98 current slots to make the reclaimed amount the only possible choice.
        $occupy=$pdo->prepare("INSERT INTO payment_amount_registry(subject_type,subject_id,transfer_amount) VALUES('monthly',?,?)");for($delta=1;$delta<=99;$delta++)if($delta!==42)$occupy->execute([9000000+$delta,Dormitory\Support\Validator::decimalString(777700+$delta)]);
        $input=['room_id'=>$old['room_id'],'check_in_date'=>$today,'check_out_date'=>$tomorrow,'guests'=>1];$quote=$app->dailyBookings()->quote($input);$new=$app->dailyBookings()->createPublic($input+['quote_token'=>$quote['quote_token'],'full_name'=>'New quarantine guest','phone'=>'0899999911','idempotency_key'=>$key('reuse-new',$old['id'])]);$qr=$service->reserve($new['id'],$new['access_token']);$assert($qr['amount']===$old['amount']);
        $q=$pdo->prepare("SELECT status FROM payment_amount_registry WHERE subject_type='daily' AND subject_id=?");$q->execute([$old['id']]);$assert($q->fetchColumn()==='released');
        $reference='QUARANTINE-OLD-BANK';$paidOld=$service->upload($old['id'],$old['access_token'],$image());$assert($paidOld['status']==='verified'&&$paidOld['booking_status']==='expired'&&$paidOld['refund_needed']);$assert(!$service->statusForOwner($new['id'])['paid']);
        $duplicate=$service->upload($new['id'],$new['access_token'],$image());$assert($duplicate['status']==='rejected','Reused amount must not bypass global bank identity');$reference='QUARANTINE-NEW-BANK';$paidNew=$service->upload($new['id'],$new['access_token'],$image());$reference=null;$assert($paidNew['status']==='verified'&&$paidNew['booking_status']==='confirmed');
        $q->execute([$old['id']]);$assert($q->fetchColumn()==='released','Late old proof reactivated a released slot');$rejectSql(fn()=>$pdo->prepare("UPDATE payment_amount_registry SET status='settled',settled_at=UTC_TIMESTAMP(6) WHERE subject_type='daily' AND subject_id=?")->execute([$old['id']]),'GLOBAL_AMOUNT_IMMUTABLE');
        $assert($service->statusForOwner($old['id'])['refund_needed']&&$service->statusForOwner($new['id'])['paid']);$q=$pdo->prepare('SELECT COUNT(*) FROM daily_transfer_instructions WHERE transfer_amount=?');$q->execute([$old['amount']]);$assert((int)$q->fetchColumn()===2,'Immutable instruction history must allow equal historical amounts');
    });
    $test('early release and pending evidence remain protected by the database quarantine guard',function()use($expiredFixture,$pdo,$service,$image,$app,$assert,$rejectSql,&$mode):void{
        $early=$expiredFixture('8888.00','0.12','EARLY',1);$rejectSql(fn()=>$pdo->prepare("UPDATE payment_amount_registry SET status='released' WHERE subject_type='daily' AND subject_id=?")->execute([$early['id']]),'DAILY_AMOUNT_QUARANTINE_ACTIVE');
        $pending=$expiredFixture('8889.00','0.13','PENDING',8);$mode='timeout';$receipt=$service->upload($pending['id'],$pending['access_token'],$image());$mode='verified';$assert($receipt['status']==='pending');$rejectSql(fn()=>$pdo->prepare("UPDATE payment_amount_registry SET status='released' WHERE subject_type='daily' AND subject_id=?")->execute([$pending['id']]),'DAILY_AMOUNT_QUARANTINE_ACTIVE');
        $app->database()->transaction(function(PDO $pdo)use($app):void{$app->limiter()->lockBucket('transfer-allocation','global');(new PaymentEvidenceRegistry($app))->reclaimAmounts($pdo);});$q=$pdo->prepare("SELECT status FROM payment_amount_registry WHERE subject_type='daily' AND subject_id=?");$q->execute([$pending['id']]);$assert($q->fetchColumn()==='reserved');$q->execute([$early['id']]);$assert($q->fetchColumn()==='reserved');
    });
    $test('settled amounts leave quarantine after seven days without changing the paid receipt',function()use($expiredFixture,$app,$pdo,$image,$assert,$rejectSql):void{
        $old=$expiredFixture('9990.00','0.14','SETTLED',8);[$absolute,$path,$mime,$hmac]=$app->payments()->storeEvidence($image(),$old['id'],$old['id']);
        $pdo->prepare("INSERT INTO daily_payments(booking_id,amount,transfer_amount,method,status,slip_path,slip_mime,slip_hmac) VALUES(?,'9990.00',?,'slip','pending',?,?,?)")->execute([$old['id'],$old['amount'],$path,$mime,$hmac]);$paymentId=(int)$pdo->lastInsertId();$registry=new PaymentEvidenceRegistry($app);
        $app->database()->transaction(function(PDO $pdo)use($registry,$paymentId,$hmac,$old):void{$registry->claimSlip($pdo,'daily',$paymentId,$hmac);if(!$registry->claimTransaction($pdo,'daily',$paymentId,'QUARANTINE-SETTLED-BANK'))throw new RuntimeException('Fixture bank reference conflict');$pdo->prepare("UPDATE daily_payments SET status='verified',transaction_ref='QUARANTINE-SETTLED-BANK',verified_at=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 8 DAY) WHERE id=?")->execute([$paymentId]);$pdo->prepare("UPDATE payment_amount_registry SET status='settled',settled_at=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 8 DAY) WHERE subject_type='daily' AND subject_id=?")->execute([$old['id']]);});
        $app->database()->transaction(function(PDO $pdo)use($app,$registry):void{$app->limiter()->lockBucket('transfer-allocation','global');$registry->reclaimAmounts($pdo);});$q=$pdo->prepare("SELECT status,active_amount FROM payment_amount_registry WHERE subject_type='daily' AND subject_id=?");$q->execute([$old['id']]);$allocation=$q->fetch();$assert($allocation['status']==='released'&&$allocation['active_amount']===null);$q=$pdo->prepare('SELECT status,transaction_ref FROM daily_payments WHERE id=?');$q->execute([$paymentId]);$paid=$q->fetch();$assert($paid['status']==='verified'&&$paid['transaction_ref']==='QUARANTINE-SETTLED-BANK');
    });
    $test('a rejected wrong daily context cannot poison the same canonical proof or bank reference for the correct booking',function()use($make,$service,$image,$pdo,$assert,$expect,&$forcedAmount,&$reference):void{
        $wrong=$make('75.00');$correct=$make('50.00');$service->reserve($wrong['id'],$wrong['access_token']);$qr=$service->reserve($correct['id'],$correct['access_token']);$file=$image();$forcedAmount=$qr['amount'];$reference='REVIEW-WRONG-DAILY-CONTEXT';
        $rejected=$service->upload($wrong['id'],$wrong['access_token'],$file);$assert($rejected['status']==='rejected'&&$rejected['transaction_ref']===null);
        $q=$pdo->prepare('SELECT claim_status,active_slip_hmac,active_txn_ref FROM payment_evidence_registry WHERE subject_type=\'daily\' AND subject_id=?');$q->execute([$rejected['id']]);$claim=$q->fetch();$assert($claim['claim_status']==='released'&&$claim['active_slip_hmac']===null&&$claim['active_txn_ref']===null);
        $paid=$service->upload($correct['id'],$correct['access_token'],$file);$assert($paid['status']==='verified'&&$paid['transaction_ref']===$reference&&$paid['booking_status']==='confirmed');
        $other=$make();$service->reserve($other['id'],$other['access_token']);$expect(fn()=>$service->upload($other['id'],$other['access_token'],$file),'DUPLICATE_SLIP');
        $q=$pdo->prepare('SELECT COUNT(*) FROM daily_payments WHERE transaction_ref=? AND status=\'verified\'');$q->execute([$reference]);$assert((int)$q->fetchColumn()===1);$forcedAmount=null;$reference=null;
    });
    $test('monthly rejection preserves history but allows the same file to verify once in the correct daily context',function()use($make,$service,$monthlyService,$image,$app,$owner,$today,$assert,$pdo,&$forcedAmount,&$reference):void{
        $room=$app->rooms()->create(['room_code'=>'REVIEW-WRONG-MONTHLY','floor'=>1,'room_type'=>'Fixture','monthly_rent'=>'90.00']);$period=substr($today,0,7);$resident=$app->bookings()->createAdminResident($owner,['room_id'=>$room['id'],'full_name'=>'Wrong context monthly fixture','phone'=>'0899999921','move_in_date'=>$period.'-01','opening_water_reading'=>'0','opening_electric_reading'=>'0','idempotency_key'=>'review-wrong-context-monthly']);$app->meters()->record(['room_id'=>$room['id'],'period'=>$period,'water_current'=>'0','electric_current'=>'0'],$owner);$billing=['period'=>$period,'room_ids'=>[$room['id']],'confirm_current_period'=>true];$preview=$app->billing()->preview($billing);$bill=$app->billing()->bulk($billing+['preview_token'=>$preview['preview_token']],$owner)['created'][0];$app->transfers()->reserve($bill['id'],$resident['resident_id']);
        $correct=$make();$qr=$service->reserve($correct['id'],$correct['access_token']);$forcedAmount=$qr['amount'];$reference='REVIEW-MONTHLY-WRONG-CONTEXT';$file=$image();$old=$monthlyService->upload($bill['id'],$resident['resident_id'],$file);$assert($old['status']==='rejected'&&$old['transaction_ref']===null);
        $q=$pdo->prepare('SELECT slip_hmac,provider_payload FROM payments WHERE id=?');$q->execute([$old['id']]);$raw=$q->fetch();$paid=$service->upload($correct['id'],$correct['access_token'],$file);$assert($paid['status']==='verified'&&$paid['transaction_ref']===$reference);
        $q->execute([$old['id']]);$assert($q->fetch()===$raw,'Reusing rejected proof must preserve its raw historical evidence');$forcedAmount=null;$reference=null;
    });
    $test('closed unknown evidence stays unpaid and visible, can be retried safely, and active older receipts outrank newer rejections',function()use($make,$service,$image,$pdo,$assert,$expect,$owner,$key,&$mode,&$calls):void{
        $b=$make();$service->reserve($b['id'],$b['access_token']);$file=$image();$mode='timeout';$p=$service->upload($b['id'],$b['access_token'],$file);$mode='verified';
        $pdo->prepare('UPDATE daily_payments SET verification_token=?,verification_lease_until=DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 60 SECOND) WHERE id=?')->execute([str_repeat('a',64),$p['id']]);
        $before=$calls;$replay=$service->upload($b['id'],$b['access_token'],$file);$assert($replay['status']==='pending'&&$replay['verifying']&&$replay['idempotent_replay']&&$calls===$before,'In-flight same-file replay must report its live lease without calling provider again');
        $input=['expected_version'=>1,'idempotency_key'=>$key('close-proof',$p['id']),'reason'=>'ตรวจไฟล์และข้อมูลเพิ่มเติม ยังไม่ยืนยันเงิน'];$expect(fn()=>$service->closePending($p['id'],$input,$owner),'PAYMENT_VERIFICATION_IN_PROGRESS');
        $pdo->prepare('UPDATE daily_payments SET verification_token=NULL,verification_lease_until=NULL WHERE id=?')->execute([$p['id']]);$closed=$service->closePending($p['id'],$input,$owner);$assert($closed['status']==='closed'&&$closed['can_retry']&&!$closed['verifying']);$assert($service->closePending($p['id'],$input,$owner)['idempotent_replay']);
        $s=$service->statusForOwner($b['id']);$assert(!$s['paid']&&$s['has_closed_unresolved']&&count($s['closed_payments'])===1&&!$s['can_generate_qr']&&!$s['can_upload']);$expect(fn()=>$service->upload($b['id'],$b['access_token'],$image()),'DAILY_PAYMENT_REVIEW_REQUIRED');
        $before=$calls;$repeat=$service->upload($b['id'],$b['access_token'],$file);$assert($repeat['status']==='closed'&&$repeat['idempotent_replay']&&$calls===$before);
        $mode='wrong_amount';$replacement=$service->uploadForOwner($b['id'],$image(),$owner);$mode='verified';$assert($replacement['status']==='rejected');$retried=$service->retry($p['id']);$assert($retried['status']==='verified'&&$retried['booking_status']==='confirmed');$s=$service->statusForOwner($b['id']);$assert($s['paid']&&$s['payment']['id']===$p['id'],'An older re-opened verified receipt must outrank a newer rejected row');
        $lookup=$service->ownerRequestStatus($b['id'],'close',$input['idempotency_key'],$owner);$assert($lookup['found']&&$lookup['result']['status']==='verified');$missing=$service->ownerRequestStatus($b['id'],'cash',$key('never-arrived',$b['id']),$owner);$assert(!$missing['found']&&!$missing['definitive_failure']);
    });
    $test('owner restores the exact missing private evidence and verifies a guest who lost the access link without changing identity',function()use($make,$service,$image,$app,$owner,$pdo,$assert,$expect,&$mode):void{
        $b=$make();$service->reserveForOwner($b['id'],$owner);$file=$image();$mode='timeout';$p=$service->uploadForOwner($b['id'],$file,$owner);$mode='verified';$q=$pdo->prepare('SELECT * FROM daily_payments WHERE id=?');$q->execute([$p['id']]);$raw=$q->fetch();$path=$app->payments()->evidencePath($raw);unlink($path);
        $s=$service->statusForOwner($b['id']);$assert($s['payment']['can_restore']&&!$s['payment']['can_retry']&&$s['payment']['evidence_error']==='SLIP_FILE_MISSING');$expect(fn()=>$service->restoreEvidence($p['id'],$image(),$owner),'SLIP_RESTORE_MISMATCH');
        $restored=$service->restoreEvidence($p['id'],$file,$owner);$assert($restored['evidence_restored']&&$restored['evidence_available']);$q->execute([$p['id']]);$assert($q->fetch()===$raw,'Evidence repair must not rewrite immutable payment or monetary fields');$again=$service->restoreEvidence($p['id'],$file,$owner);$assert($again['idempotent_replay']&&!$again['evidence_restored']);$paid=$service->retry($p['id']);$assert($paid['status']==='verified');
    });
    $test('owner can restore an exact canonical JPEG backup without a second lossy encoding',function()use($make,$service,$app,$owner,$pdo,$assert,&$images,&$mode):void{
        $b=$make();$service->reserveForOwner($b['id'],$owner);$source=tempnam($app->config->root.'/storage','review-jpeg-');$images[]=$source;$picture=imagecreatetruecolor(32,32);for($x=0;$x<32;$x++)for($y=0;$y<32;$y++)imagesetpixel($picture,$x,$y,imagecolorallocate($picture,$x*7,$y*7,($x+$y)*3));imagejpeg($picture,$source,73);unset($picture);$mode='timeout';$p=$service->uploadForOwner($b['id'],['error'=>UPLOAD_ERR_OK,'tmp_name'=>$source,'size'=>filesize($source)],$owner);$mode='verified';
        $q=$pdo->prepare('SELECT * FROM daily_payments WHERE id=?');$q->execute([$p['id']]);$record=$q->fetch();$path=$app->payments()->evidencePath($record);$backup=tempnam($app->config->root.'/storage','review-jpeg-backup-');$images[]=$backup;copy($path,$backup);file_put_contents($path,'corrupt fixture');
        $restored=$service->restoreEvidence($p['id'],['error'=>UPLOAD_ERR_OK,'tmp_name'=>$backup,'size'=>filesize($backup)],$owner);$assert($restored['evidence_restored']&&hash_equals($record['slip_hmac'],hash_hmac_file('sha256',$path,$app->config->appKey())));
    });
    $test('owner privilege changed during provider I/O rolls back financial confirmation and a fresh owner can retry the same proof once',function()use($make,$service,$app,$owner,$pdo,$assert,$expect,$image,&$onRequest,&$reference):void{
        $b=$make();$service->reserveForOwner($b['id'],$owner);$q=$pdo->prepare('SELECT auth_version FROM admin_users WHERE id=?');$q->execute([$owner]);$version=(int)$q->fetchColumn();
        $actorCache=new ReflectionProperty(Dormitory\Application::class,'actorCache');$actorCache->setValue($app,['type'=>'admin','id'=>$owner,'role'=>'owner','auth_version'=>$version,'username'=>'daily_payment_owner']);
        $commitOwner=new ReflectionMethod(Dormitory\Http\DailyRoutes::class,'currentOwnerForCommit');$reference='REVIEW-REVOKED-OWNER-COMMIT';
        $onRequest=static function()use($pdo,$owner):void{$pdo->prepare('UPDATE admin_users SET auth_version=auth_version+1,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$owner]);};
        $expect(fn()=>$service->uploadForOwner($b['id'],$image(),$owner,static function(array $payment)use($commitOwner,$app):void{$commitOwner->invoke(null,$app);}), 'OWNER_ACCESS_REVOKED');$onRequest=null;
        $s=$service->statusForOwner($b['id']);$assert(!$s['paid']&&$s['payment']['status']==='pending'&&!$s['payment']['verifying']&&$s['booking_status']==='pending','Revoked owner must not commit a paid/confirmed response or discard reserved proof');
        $q->execute([$owner]);$freshVersion=(int)$q->fetchColumn();$actorCache->setValue($app,['type'=>'admin','id'=>$owner,'role'=>'owner','auth_version'=>$freshVersion,'username'=>'daily_payment_owner']);
        $paid=$service->retry($s['payment']['id'],static function(array $payment)use($commitOwner,$app):void{$commitOwner->invoke(null,$app);});$assert($paid['status']==='verified'&&$paid['booking_status']==='confirmed');
        $q=$pdo->prepare("SELECT COUNT(*) FROM daily_payments WHERE booking_id=? AND status='verified'");$q->execute([$b['id']]);$assert((int)$q->fetchColumn()===1);$reference=null;$actorCache->setValue($app,false);
    });
}finally{foreach($images as$path)if(is_file($path))@unlink($path);}
echo "{$passed} daily-payment integration groups passed; no external provider calls\n";
