<?php
declare(strict_types=1);
use Dormitory\Http\HttpException;
use Dormitory\Security\Password;
if(PHP_SAPI!=='cli'||getenv('APP_ENV')!=='testing'||preg_match('/^appj_[a-z0-9_]+$/D',(string)getenv('DB_DATABASE'))!==1)exit(64);
$app=require dirname(__DIR__).'/bootstrap.php';$pdo=$app->database()->pdo();
if((int)$pdo->query('SELECT COUNT(*) FROM rooms')->fetchColumn()!==0)throw new RuntimeException('Fresh isolated database required');
$passed=0;$check=static function(string $name,bool $ok)use(&$passed):void{if(!$ok)throw new RuntimeException($name);$passed++;fwrite(STDOUT,"PASS {$name}\n");};
$expect=static function(callable $fn,string $code):HttpException{try{$fn();}catch(HttpException $e){if($e->errorCode!==$code)throw new RuntimeException('Expected '.$code.', got '.$e->errorCode);return $e;}throw new RuntimeException('Expected '.$code);};
$q=$pdo->prepare("INSERT INTO admin_users(username,password_hash,role,auth_version,active)VALUES('meter_owner',?,'owner',1,1)");$q->execute([Password::hash('Meter-fixture-only-2026!')]);$owner=(int)$pdo->lastInsertId();
$now=new DateTimeImmutable('first day of this month',new DateTimeZone('Asia/Bangkok'));$moveIn=$now->modify('-1 day')->format('Y-m-d');$first=substr($moveIn,0,7);$prior=$now->modify('-1 month')->format('Y-m');$period=$now->format('Y-m');
$room=$app->rooms()->create(['room_code'=>'RECOVER-101','floor'=>1,'room_type'=>'Test','monthly_rent'=>'3500.00']);$id=$room['id'];
$app->bookings()->createAdminResident($owner,['room_id'=>$id,'full_name'=>'Meter fixture','phone'=>'0817888881','move_in_date'=>$moveIn,'opening_water_reading'=>'100.00','opening_electric_reading'=>'200.00','idempotency_key'=>'meter-fixture-occupancy-01']);
$get=static function(string $p)use($app,$id):array{return array_values(array_filter($app->meters()->list($p),static fn($r)=>$r['room_id']===$id))[0];};
$save=static fn(string $p,string $w,string $e,array $extra=[])=>$app->meters()->record(['room_id'=>$id,'period'=>$p,'water_current'=>$w,'electric_current'=>$e]+$extra,$owner);
$row=$get($period);$check('missing prior period is blocked, never labelled a vacant baseline',$row['water_locked']&&$row['water_baseline_state']==='history_gap'&&!$row['water_vacant_baseline']&&$row['water_previous']===null);
$check('recovery links to the earliest actual missing occupancy month',$row['water_issue']['recovery_period']===$first&&$row['water_issue']['required_previous_period']===$prior);
$error=$expect(fn()=>$save($period,'130','240'),'METER_HISTORY_GAP');$check('server returns Thai guidance and the same repair month',$error->details['recovery_period']===$first&&!str_contains($error->getMessage(),'An earlier'));
$check('failed record made no partial water/electric rows',(int)$pdo->query('SELECT COUNT(*) FROM meter_readings')->fetchColumn()===0);
$row=$get($first);$check('first occupied month uses actual move-in readings',$row['water_previous']==='100.00'&&$row['electric_previous']==='200.00'&&!$row['water_locked']);
$save($first,'110','210');$save($prior,'120','220');$row=$get($period);$check('filling missing months unlocks current month with the exact prior baseline',!$row['water_locked']&&$row['water_previous']==='120.00'&&$row['electric_previous']==='220.00');
$saved=$save($period,'130','240',['water_version'=>$row['water_version'],'electric_version'=>$row['electric_version']]);
$check('saved values return exact units and fresh server edit versions',$saved['water']['units']==='10.00'&&$saved['electric']['units']==='20.00'&&$saved['water_version']!==$row['water_version']);
$loaded=$get($period);$versions=['water_version'=>$loaded['water_version'],'electric_version'=>$loaded['electric_version']];
$save($period,'131','241',$versions);$expect(fn()=>$save($period,'140','250',$versions),'METER_CHANGED');
$check('a stale second tab cannot overwrite either meter',$get($period)['water_current']==='131.00'&&$get($period)['electric_current']==='241.00');
$replay=$save($period,'131','241',$versions);$check('an unchanged retry remains harmless even with an old version',count($replay['unchanged_meter_types'])===2);
$fresh=$get($period);$save($period,'132','242',['water_version'=>$fresh['water_version'],'electric_version'=>$fresh['electric_version']]);$check('latest unbilled month can be edited again',$get($period)['water_current']==='132.00');
$expect(fn()=>$save($period,'150','1'),'METER_ROLLBACK');$check('invalid electric reading does not partially save water',$get($period)['water_current']==='132.00');
$locked=$get($prior);$check('earlier rows explain that a later month depends on them',$locked['water_locked']&&$locked['water_lock_reason']==='later_reading');$expect(fn()=>$save($prior,'125','225'),'METER_HISTORY_LOCKED');
$app->billing()->updateSettings(['water_rate'=>'18.00','electric_rate'=>'7.00','due_days'=>7],$owner);
$bill=['period'=>$period,'room_ids'=>[$id],'confirm_current_period'=>true];$preview=$app->billing()->preview($bill);$app->billing()->bulk($bill+['preview_token'=>$preview['preview_token']],$owner);
$check('billed meters stay protected and show the precise reason',$get($period)['is_billed']&&$get($period)['water_lock_reason']==='billed');$expect(fn()=>$save($period,'135','245'),'METER_ALREADY_BILLED');
$vacant=$app->rooms()->create(['room_code'=>'VACANT-102','floor'=>1,'room_type'=>'Test','monthly_rent'=>'3000.00']);
$all=$app->meters()->list($period);$v=array_values(array_filter($all,fn($r)=>$r['room_id']===$vacant['id']))[0];
$check('only a truly vacant new meter gets the zero-usage baseline',$v['water_vacant_baseline']&&!$v['water_locked']&&$v['occupancy_id']===null);
$baseline=$app->meters()->record(['room_id'=>$vacant['id'],'period'=>$period,'water_current'=>'500','electric_current'=>'800'],$owner);
$check('vacant baseline preserves the measured value instead of inventing zero',$baseline['water']['previous']==='500.00'&&$baseline['water']['units']==='0.00');
$room2=$app->rooms()->create(['room_code'=>'OLD-PHYSICAL-103','floor'=>1,'room_type'=>'Test','monthly_rent'=>'3000.00']);
$app->meters()->record(['room_id'=>$room2['id'],'period'=>$now->modify('-3 months')->format('Y-m'),'water_current'=>'5','electric_current'=>'10'],$owner);
$app->bookings()->createAdminResident($owner,['room_id'=>$room2['id'],'full_name'=>'Different history','phone'=>'0817888882','move_in_date'=>$moveIn,'opening_water_reading'=>'50.00','opening_electric_reading'=>'100.00','idempotency_key'=>'meter-fixture-occupancy-02']);
$physical=array_values(array_filter($app->meters()->list($period),fn($r)=>$r['room_id']===$room2['id']))[0];
$check('unoccupied physical history cannot become a current resident previous reading',$physical['water_previous']===null&&$physical['water_issue']['recovery_period']===$first);
fwrite(STDOUT,"{$passed} meter recovery MySQL checks passed; no external API calls\n");
