<?php declare(strict_types=1); ?>
<section class="admin-view" data-admin-view="daily" data-daily-admin aria-labelledby="daily-admin-title" hidden>
  <div class="section-heading"><div><p class="eyebrow">งานห้องพักรายวัน</p><h2 id="daily-admin-title">จองรายวัน</h2><p>เพิ่มการจอง → รับเงิน → เช็กอิน → คืนหรือหักค่าประกัน → เช็กเอาต์ → ทำความสะอาด</p></div><div class="section-heading-actions"><button type="button" class="button button-secondary" data-refresh="daily">โหลดข้อมูลล่าสุด</button><button type="button" class="button button-primary" id="daily-owner-create" data-action-help aria-describedby="daily-admin-note daily-setup-guide" disabled>เพิ่มการจองรายวัน</button></div></div>
  <aside id="daily-setup-guide" class="panel daily-setup-guide" hidden><h3>เริ่มต้นด้วยการตั้งห้องรายวัน</h3><p>ยังไม่มีห้องรายวันให้เลือก ไปที่ “ห้องรายวัน” แล้วเพิ่มห้อง ตั้งราคาต่อคืน จำนวนผู้พักสูงสุด และค่าประกัน ข้อมูลห้องรายเดือนจัดการในส่วนงานรายเดือนแยกกัน</p><div class="form-actions"><button type="button" class="button button-primary" data-overview-jump="daily-rooms">ไปตั้งห้องรายวัน</button><a class="button button-secondary" href="/daily" target="_blank" rel="noopener">ดูหน้าจองของลูกค้า</a></div><p class="field-hint">รับเงินสดพร้อมใบรับเงินได้ หากต้องการรับโอนและตรวจสลิปอัตโนมัติ ให้ตั้งค่าผู้ให้บริการตรวจสลิปและบัญชีผู้รับเงินใน “ตั้งค่า” ก่อน</p></aside>
  <aside id="daily-owner-recovery" class="security-note stack-form" role="alert" hidden><strong>ยังไม่ทราบผลรายการเดิม</strong><p id="daily-owner-recovery-text">ตรวจผลด้วยหมายเลขคำขอเดิมก่อนเริ่มงานใหม่ ห้ามรับหรือคืนเงินจริงซ้ำ</p><button id="daily-owner-recovery-open" type="button" class="button button-primary">เปิดรายการเดิมเพื่อตรวจผล</button></aside>
  <div class="stats-grid stats-grid-four" id="daily-admin-stats"><article class="stat-card"><span>เข้าในวันนี้</span><strong data-daily-count="arrivals">—</strong></article><article class="stat-card"><span>ครบกำหนดออก / เกินกำหนด</span><strong data-daily-count="departures">—</strong></article><article class="stat-card"><span>รอยืนยันในช่วงที่เลือก</span><strong data-daily-count="pending">—</strong></article><article class="stat-card"><span>รอทำความสะอาด</span><strong data-daily-count="cleaning">—</strong></article></div>
  <form id="daily-admin-filter" class="toolbar"><label><span>วันเริ่มต้น</span><input name="from" type="date" required></label><label><span>วันสิ้นสุด (ไม่รวมวันที่นี้)</span><input name="to" type="date" required></label><label><span>สถานะ</span><select name="status"><option value="">ทั้งหมด</option><option value="pending">รอยืนยัน</option><option value="confirmed">ยืนยันแล้ว</option><option value="checked_in">เข้าพักแล้ว</option><option value="checked_out">เช็กเอาต์แล้ว</option><option value="cancelled">ยกเลิก</option><option value="expired">หมดอายุ</option><option value="no_show">ไม่มาเข้าพัก</option></select></label><button type="submit" class="button button-secondary">แสดงรายการ</button></form>
  <p class="field-hint">แสดงการจองที่มีช่วงพักทับวันที่เลือก รวมผู้พักที่ยังไม่เช็กเอาต์ซึ่งถึงหรือเกินกำหนดออกแล้ว</p>
  <p id="daily-admin-error" class="form-error" role="alert" hidden></p>
  <p id="daily-admin-note" role="status">กำลังรอโหลดข้อมูล</p>
  <div class="panel table-panel"><div class="table-scroll" tabindex="0" role="region" aria-label="การจองรายวัน"><table class="daily-booking-table"><thead><tr><th>การจอง / ผู้พัก</th><th>ห้อง</th><th>เข้า / ออก</th><th>คน / คืน</th><th>ยอดรวม</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody id="daily-admin-rows"></tbody></table></div></div>
  <div class="form-actions"><button id="daily-booking-load-more" type="button" class="button button-secondary" hidden>โหลดรายการจองเพิ่มเติม</button></div>
  <details class="daily-secondary-options"><summary>ปฏิทินห้องตามช่วงที่เลือก</summary><p class="field-hint">เปิดขายรอบถัดไปได้หลังวันเช็กเอาต์ที่ระบุในการจองและทำความสะอาดแล้ว หากออกก่อนกำหนด วันที่เหลือยังถูกกันไว้ตามการจองเดิม</p><div class="panel table-panel"><div id="daily-calendar" class="table-scroll" tabindex="0" role="region" aria-label="ปฏิทินห้องรายวัน"></div></div></details>
  <h3>ห้องและช่วงปิดขาย</h3><p class="field-hint">สถานะด้านล่างแสดงงานทำความสะอาด ตรวจช่วงว่างในปฏิทินก่อนรับผู้พัก</p><div id="daily-housekeeping" class="daily-room-operations"></div>
</section>
<dialog class="modal" id="daily-owner-create-dialog" aria-labelledby="daily-owner-create-title"><form id="daily-owner-create-form" data-guard-draft class="modal-card modal-card-wide"><div class="modal-header"><h2 id="daily-owner-create-title">เพิ่มการจองรายวัน</h2><button type="button" class="text-control" data-close-dialog aria-label="ปิด">ปิด</button></div><p id="daily-owner-create-help">เลือกห้องและกรอกข้อมูลให้ครบ กด “ตรวจห้องและยอดก่อนสร้าง” แล้วจึงกด “สร้างการจองตามยอดนี้” หลังสร้างให้รับเงินจากรายละเอียดการจองก่อนเช็กอิน</p><div class="form-grid form-grid-two">
  <label class="field"><span>ห้องรายวัน</span><select name="room_id" required></select><small id="daily-owner-room-help">เลือกห้องเพื่อดูจำนวนผู้พักสูงสุด</small></label><label class="field"><span>ผู้พัก (คน)</span><input name="guests" type="number" min="1" max="20" step="1" value="1" required></label>
  <label class="field"><span>วันเช็กอิน</span><input name="check_in_date" type="date" required></label><label class="field"><span>วันเช็กเอาต์</span><input name="check_out_date" type="date" required></label>
  <label class="field"><span>ชื่อ–นามสกุล</span><input name="full_name" minlength="2" maxlength="150" autocomplete="name" required></label><label class="field"><span>เบอร์มือถือ</span><input name="phone" type="tel" maxlength="20" required></label>
  </div><div id="daily-owner-quote-summary" class="daily-summary" aria-live="polite"></div><p class="form-error" id="daily-owner-create-error" role="alert" hidden></p><div class="form-actions"><button type="button" class="button button-ghost" data-close-dialog>กลับ</button><button id="daily-owner-review" type="button" class="button button-secondary">ตรวจห้องและยอดก่อนสร้าง</button><button class="button button-primary" type="submit" data-action-help aria-describedby="daily-owner-create-help daily-owner-quote-summary daily-owner-create-error" disabled>สร้างการจองตามยอดนี้</button></div></form></dialog>
<dialog class="modal" id="daily-owner-detail-dialog" aria-labelledby="daily-owner-detail-title"><div class="modal-card modal-card-wide stack-form"><div class="modal-header"><h2 id="daily-owner-detail-title">รายละเอียดการจองรายวัน</h2><button class="text-control" type="button" data-close-dialog aria-label="ปิด">ปิด</button></div><div id="daily-owner-detail-summary" class="daily-summary"></div><aside id="daily-owner-next-step" class="daily-next-step" role="status" hidden></aside><p id="daily-owner-payment-status" role="status"></p><div id="daily-owner-payment-totals" class="daily-summary"></div><p id="daily-owner-detail-error" class="form-error" role="alert" hidden></p><button id="daily-owner-detail-refresh" type="button" class="button button-secondary">โหลดสถานะการเงินล่าสุด</button><div id="daily-owner-payment-actions" class="stack-form" hidden>
  <form id="daily-cash-form" data-guard-draft class="stack-form"><h3>บันทึกเงินสดที่รับแล้ว</h3><p>บันทึกยอดเต็มการจองเท่านั้น ใช้เลขใบรับเงินที่ออกให้ผู้พัก</p><label class="field"><span>เลขใบรับเงิน</span><input name="reference" minlength="3" maxlength="191" required></label><button type="submit" class="button button-primary">บันทึกรับเงินสดเต็มยอด</button></form>
  <form id="daily-refund-form" data-guard-draft class="stack-form"><h3>บันทึกเงินคืนที่โอนแล้ว</h3><p>ทำรายการคืนเงินจริงก่อนบันทึก เลือกยอดคืนจากยอดที่คืนได้ด้านบน</p><div class="form-grid form-grid-two"><label class="field"><span>ยอดคืน (บาท)</span><input name="amount" type="number" min="0.01" step="0.01" required></label><label class="field"><span>เลขอ้างอิงโอนเงินออก</span><input name="reference" minlength="3" maxlength="191" required></label></div><label class="field"><span>เหตุผลคืนเงิน</span><input name="reason" minlength="3" maxlength="450" required></label><button type="submit" class="button button-secondary">บันทึกเงินคืน</button></form>
  <form id="daily-deposit-form" data-guard-draft class="stack-form"><h3>หักค่าประกันตามผลตรวจห้อง</h3><label class="field"><span>ยอดหักค่าประกัน (บาท)</span><input name="retained_amount" type="number" min="0.01" step="0.01" required></label><label class="field"><span>เหตุผล / รายการเสียหาย</span><input name="reason" minlength="3" maxlength="450" required></label><button type="submit" class="button button-secondary">บันทึกการหักค่าประกัน</button></form>
  <div id="daily-owner-slip-actions" class="form-actions"></div>
  <p id="daily-owner-bank-help" class="field-hint"></p><button id="daily-owner-load-qr" data-action-help aria-describedby="daily-owner-bank-help daily-owner-next-step" type="button" class="button button-secondary" disabled>แสดง QR สำหรับการจองนี้</button><div id="daily-owner-qr-stage" class="qr-stage"></div>
  <form id="daily-close-form" class="stack-form" data-guard-draft hidden><h3>พักการตรวจหลักฐาน</h3><p id="daily-close-summary"></p><p>ยอดเงินยังไม่ยืนยันและหลักฐานยังถูกเก็บไว้ ห้ามรับหรือให้ผู้พักโอนซ้ำ เมื่อแก้ปัญหาแล้วให้ตรวจหลักฐานเดิมต่อ</p><label class="field"><span>เหตุผลที่พักการตรวจ</span><textarea name="reason" minlength="3" maxlength="450" rows="3" required></textarea></label><button type="submit" class="button button-secondary">ยืนยันพักการตรวจหลักฐานเดิม</button></form>
  <form id="daily-owner-upload-form" class="stack-form" data-guard-draft hidden><h3>ส่งหลักฐานโอนให้ผู้พัก</h3><p>ใช้เมื่อผู้พักโอนตามยอดเดิมแล้ว แต่เปิดหน้าจองเดิมไม่ได้หรือส่งสลิปหลังหมดเวลา การส่งหลักฐานไม่ได้ยืนยันห้องที่หมดเวลาให้กลับมา</p><label class="field"><span>สลิปจากผู้พัก</span><input name="slip" type="file" accept="image/jpeg,image/png,image/webp" required><small>JPEG, PNG หรือ WebP ไม่เกิน 4 MiB</small></label><button type="submit" class="button button-primary">ส่งหลักฐานให้ระบบตรวจ</button></form>
  <form id="daily-owner-restore-form" class="stack-form" data-guard-draft hidden><h3>ซ่อมหลักฐานเดิมที่อ่านไม่ได้</h3><p id="daily-owner-restore-summary"></p><p>เลือกไฟล์ต้นฉบับที่เคยส่ง ระบบจะยอมรับเฉพาะหลักฐานเดิมที่ตรงกัน หลังซ่อมแล้วจึงกดตรวจสลิปเดิมซ้ำได้ การซ่อมไฟล์ไม่ทำให้ยอดเป็นชำระแล้ว</p><label class="field"><span>ไฟล์ต้นฉบับ</span><input name="slip" type="file" accept="image/jpeg,image/png,image/webp" required><small>JPEG, PNG หรือ WebP ไม่เกิน 4 MiB</small></label><button type="submit" class="button button-secondary">ซ่อมไฟล์หลักฐานเดิม</button></form>
</div></div></dialog>
<dialog class="modal" id="daily-block-dialog" aria-labelledby="daily-block-title"><form id="daily-block-form" class="modal-card stack-form" data-guard-draft><div class="modal-header"><h2 id="daily-block-title">ปิดขายห้องตามช่วงวัน</h2><button type="button" class="text-control" data-close-dialog aria-label="ปิด">ปิด</button></div><p id="daily-block-room"></p><div class="form-grid form-grid-two"><label class="field"><span>วันเริ่มปิดขาย</span><input name="start_date" type="date" required></label><label class="field"><span>วันสิ้นสุด (ไม่รวมวันนี้)</span><input name="end_date" type="date" required></label></div><label class="field"><span>เหตุผล</span><textarea name="reason" rows="3" minlength="3" maxlength="500" required></textarea></label><p class="form-error" id="daily-block-error" role="alert" hidden></p><div class="form-actions"><button type="button" class="button button-ghost" data-close-dialog>กลับ</button><button type="submit" class="button button-primary">ปิดขายตามช่วงนี้</button></div></form></dialog>
