-- AUTO-GENERATED FRESH-INSTALL BUNDLE. DO NOT EDIT THIS FILE DIRECTLY.
-- Import this one file from phpMyAdmin's server-level Import tab.
-- It creates/uses the `dormitory` database, current schema, triggers, and
-- safe baseline settings. It contains no owner, room, resident, demo data,
-- PromptPay number, LINE channel credential, or slip-provider credential.
-- Fresh installations only: it stops before changing a non-empty database.
-- Never use a force/continue-on-error import option with this file.
-- Regenerate: php scripts/build_install_sql.php
-- Verify current: php scripts/build_install_sql.php --check
-- Source digest: e67b6e92bf0839d5011447a1528f91488ae3ebc50b7dbcb0880bb0a348f4ba36
-- BEGIN database/00-create-database.sql
-- Advanced/manual fresh-install step. For the simplest new installation,
-- import database/install.sql once instead. Run this standalone file from the
-- phpMyAdmin server-level SQL tab only when the `dormitory` database does not
-- exist yet. It intentionally creates no user and grants no privileges.
--
-- Required server: Oracle MySQL 8.0.16+ (not MariaDB).

CREATE DATABASE IF NOT EXISTS dormitory
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE dormitory;

SELECT DATABASE() AS selected_database, VERSION() AS mysql_version;

-- Only when this file is run standalone (not through install.sql), keep
-- `dormitory` selected in phpMyAdmin and import:
--   1. database/schema.sql
--   2. database/defaults.sql
-- Import database/demo.sql only on an isolated local-development database.
-- END database/00-create-database.sql

-- BEGIN generated fresh-database guard
-- Refuse to touch an existing/partial database before schema.sql can create,
-- replace, or drop any object. Do not import this bundle with a force/continue
-- option; use database/migrations for an installed system instead.
SET @dormitory_existing_object_count := (
    SELECT COUNT(*)
      FROM information_schema.tables
     WHERE table_schema = DATABASE()
);
SET @dormitory_fresh_install_guard_sql := IF(
    DATABASE() = 'dormitory'
        AND @dormitory_existing_object_count = 0,
    'SELECT 1',
    'SELECT * FROM information_schema.DORMITORY_INSTALL_ABORT_DATABASE_NOT_EMPTY'
);
PREPARE dormitory_fresh_install_guard FROM @dormitory_fresh_install_guard_sql;
EXECUTE dormitory_fresh_install_guard;
DEALLOCATE PREPARE dormitory_fresh_install_guard;
-- END generated fresh-database guard

-- BEGIN database/schema.sql
-- Dormitory PHP/MySQL rewrite: FR-01 through FR-16 only.
-- Target: MySQL 8.0.16+ (CHECK constraints are enforced from 8.0.16).
-- Fresh/current-schema bootstrap only; it never creates a default account.
-- Do not use this file to upgrade a legacy installation. Back up first and run
-- database/migrations/001_integration_settings.sql when needed, followed by
-- database/migrations/002_operational_hardening.sql exactly once, then
-- database/migrations/003_append_only_guards.sql and
-- database/migrations/004_line_webhook.sql and
-- database/migrations/005_booking_active_phone.sql. Then deploy transitional
-- commit a52bc33 to every replica, verify health, back up and test restore,
-- run database/migrations/006_remove_resident_pin.sql, verify the column is
-- absent, stop notification workers, run
-- database/migrations/007_notification_worker_fencing.sql and
-- database/migrations/008_resident_access_credentials.sql, then enter a
-- maintenance window with web/worker writes stopped and run
-- database/migrations/009_occupancy_meter_baselines.sql, followed by
-- database/migrations/010_line_self_service_binding.sql,
-- database/migrations/011_line_add_friend_identity.sql,
-- database/migrations/012_move_in_request_hash.sql and
-- database/migrations/013_trigger_collation_pinning.sql. Deploy the current
-- source before reopening traffic.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Store timestamps in UTC. PHP formats them for Asia/Bangkok at the UI edge.
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('owner', 'admin') NOT NULL DEFAULT 'admin',
    auth_version INT UNSIGNED NOT NULL DEFAULT 1,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_admin_users_username (username),
    KEY idx_admin_users_created_by (created_by),
    CONSTRAINT fk_admin_users_created_by
        FOREIGN KEY (created_by) REFERENCES admin_users(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_admin_users_username
        CHECK (username REGEXP '^[A-Za-z0-9_.-]{3,64}$'),
    CONSTRAINT chk_admin_users_auth_version CHECK (auth_version >= 1),
    CONSTRAINT chk_admin_users_active CHECK (active IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS residents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(150) NOT NULL,
    phone_norm CHAR(10) NOT NULL,
    email VARCHAR(254) NULL,
    line_user_id VARCHAR(33) CHARACTER SET ascii COLLATE ascii_bin NULL,
    auth_version INT UNSIGNED NOT NULL DEFAULT 1,
    access_password_hash VARCHAR(255) NULL,
    activation_code_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    activation_expires_at DATETIME(6) NULL,
    activation_consumed_at DATETIME(6) NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_residents_phone_norm (phone_norm),
    UNIQUE KEY uq_residents_line_user_id (line_user_id),
    CONSTRAINT chk_residents_full_name CHECK (CHAR_LENGTH(TRIM(full_name)) BETWEEN 1 AND 150),
    CONSTRAINT chk_residents_phone_norm CHECK (phone_norm REGEXP '^0[0-9]{9}$'),
    CONSTRAINT chk_residents_email CHECK (email IS NULL OR CHAR_LENGTH(email) BETWEEN 3 AND 254),
    CONSTRAINT chk_residents_line_user_id CHECK (
        line_user_id IS NULL OR line_user_id REGEXP '^U[0-9a-f]{32}$'
    ),
    CONSTRAINT chk_residents_auth_version CHECK (auth_version >= 1),
    CONSTRAINT chk_residents_access_password CHECK (
        access_password_hash IS NULL
        OR CHAR_LENGTH(access_password_hash) BETWEEN 20 AND 255
    ),
    CONSTRAINT chk_residents_activation_state CHECK (
        (
            activation_code_hash IS NULL
            AND activation_expires_at IS NULL
        )
        OR (
            activation_code_hash REGEXP '^[0-9a-f]{64}$'
            AND activation_expires_at IS NOT NULL
            AND activation_consumed_at IS NULL
            AND access_password_hash IS NULL
        )
    ),
    CONSTRAINT chk_residents_password_activation CHECK (
        access_password_hash IS NULL
        OR (
            activation_code_hash IS NULL
            AND activation_expires_at IS NULL
            AND activation_consumed_at IS NOT NULL
        )
    ),
    CONSTRAINT chk_residents_active CHECK (active IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS line_link_codes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    resident_id BIGINT UNSIGNED NOT NULL,
    code_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status ENUM('pending', 'bound', 'expired', 'revoked') NOT NULL DEFAULT 'pending',
    line_user_id VARCHAR(33) CHARACTER SET ascii COLLATE ascii_bin NULL,
    expires_at DATETIME(6) NOT NULL,
    bound_at DATETIME(6) NULL,
    revoked_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    pending_resident_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN status = 'pending' THEN resident_id ELSE NULL END
        ) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uq_line_link_codes_code_hash (code_hash),
    UNIQUE KEY uq_line_link_codes_pending_resident (pending_resident_id),
    KEY idx_line_link_codes_expiry (status, expires_at),
    KEY idx_line_link_codes_resident (resident_id, created_at),
    CONSTRAINT fk_line_link_codes_resident
        FOREIGN KEY (resident_id) REFERENCES residents(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_line_link_codes_hash
        CHECK (code_hash REGEXP '^[0-9a-f]{64}$'),
    CONSTRAINT chk_line_link_codes_line_user CHECK (
        line_user_id IS NULL OR line_user_id REGEXP '^U[0-9a-f]{32}$'
    ),
    CONSTRAINT chk_line_link_codes_state CHECK (
        (
            status = 'pending'
            AND line_user_id IS NULL
            AND bound_at IS NULL
            AND revoked_at IS NULL
        )
        OR (
            status = 'bound'
            AND line_user_id IS NOT NULL
            AND bound_at IS NOT NULL
            AND revoked_at IS NULL
        )
        OR (
            status = 'expired'
            AND line_user_id IS NULL
            AND bound_at IS NULL
            AND revoked_at IS NULL
        )
        OR (
            status = 'revoked'
            AND revoked_at IS NOT NULL
            AND (
                (line_user_id IS NULL AND bound_at IS NULL)
                OR (line_user_id IS NOT NULL AND bound_at IS NOT NULL)
            )
        )
    ),
    CONSTRAINT chk_line_link_codes_timestamps CHECK (
        expires_at > created_at
        AND (
            bound_at IS NULL
            OR (bound_at >= created_at AND bound_at < expires_at)
        )
        AND (
            revoked_at IS NULL
            OR (
                revoked_at >= created_at
                AND (bound_at IS NULL OR revoked_at >= bound_at)
            )
        )
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    room_code VARCHAR(32) NOT NULL,
    floor SMALLINT UNSIGNED NOT NULL,
    room_type VARCHAR(50) NOT NULL,
    monthly_rent DECIMAL(12,2) NOT NULL,
    description TEXT NULL,
    amenities JSON NOT NULL,
    image_key VARCHAR(255) NULL,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_rooms_room_code (room_code),
    KEY idx_rooms_public (deleted_at, floor, room_code),
    CONSTRAINT chk_rooms_code CHECK (CHAR_LENGTH(TRIM(room_code)) BETWEEN 1 AND 32),
    CONSTRAINT chk_rooms_floor CHECK (floor BETWEEN 1 AND 999),
    CONSTRAINT chk_rooms_type CHECK (CHAR_LENGTH(TRIM(room_type)) BETWEEN 1 AND 50),
    CONSTRAINT chk_rooms_monthly_rent CHECK (monthly_rent > 0 AND monthly_rent <= 1000000),
    CONSTRAINT chk_rooms_amenities_array CHECK (JSON_TYPE(amenities) = 'ARRAY'),
    CONSTRAINT chk_rooms_image_key CHECK (
        image_key IS NULL OR image_key IN (
            'room-standard.jpg', 'room-deluxe.jpg',
            'room-suite.jpg', 'room-studio.jpg'
        )
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference_no VARCHAR(40) NOT NULL,
    room_id BIGINT UNSIGNED NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone_norm CHAR(10) NOT NULL,
    booked_monthly_rent DECIMAL(12,2) NOT NULL,
    status ENUM('pending', 'confirmed', 'cancelled', 'moved_in') NOT NULL DEFAULT 'pending',
    idempotency_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME(6) NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME(6) NULL,
    cancel_reason VARCHAR(500) NULL,
    resident_id BIGINT UNSIGNED NULL,
    moved_in_at DATETIME(6) NULL,
    move_in_request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    active_room_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN status IN ('pending', 'confirmed') THEN room_id ELSE NULL END
        ) STORED,
    active_phone_norm CHAR(10)
        GENERATED ALWAYS AS (
            CASE WHEN status IN ('pending', 'confirmed') THEN phone_norm ELSE NULL END
        ) STORED,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_bookings_reference_no (reference_no),
    UNIQUE KEY uq_bookings_idempotency_key (idempotency_key),
    UNIQUE KEY uq_bookings_one_active_per_room (active_room_id),
    UNIQUE KEY uq_bookings_one_active_per_phone (active_phone_norm),
    KEY idx_bookings_room_created (room_id, created_at),
    KEY idx_bookings_status_created (status, created_at),
    KEY idx_bookings_phone (phone_norm),
    KEY idx_bookings_resident (resident_id),
    CONSTRAINT fk_bookings_room
        FOREIGN KEY (room_id) REFERENCES rooms(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_confirmed_by
        FOREIGN KEY (confirmed_by) REFERENCES admin_users(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_bookings_cancelled_by
        FOREIGN KEY (cancelled_by) REFERENCES admin_users(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_bookings_resident
        FOREIGN KEY (resident_id) REFERENCES residents(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_bookings_reference CHECK (CHAR_LENGTH(TRIM(reference_no)) BETWEEN 6 AND 40),
    CONSTRAINT chk_bookings_full_name CHECK (CHAR_LENGTH(TRIM(full_name)) BETWEEN 1 AND 150),
    CONSTRAINT chk_bookings_phone CHECK (phone_norm REGEXP '^0[0-9]{9}$'),
    CONSTRAINT chk_bookings_monthly_rent CHECK (booked_monthly_rent > 0 AND booked_monthly_rent <= 1000000),
    CONSTRAINT chk_bookings_idempotency CHECK (CHAR_LENGTH(idempotency_key) BETWEEN 16 AND 64),
    CONSTRAINT chk_bookings_move_in_request_hash CHECK (
        move_in_request_hash IS NULL
        OR (
            status = 'moved_in'
            AND move_in_request_hash REGEXP '^[0-9a-f]{64}$'
        )
    ),
    CONSTRAINT chk_bookings_state CHECK (
        (status = 'pending'
            AND confirmed_at IS NULL AND cancelled_at IS NULL
            AND moved_in_at IS NULL AND resident_id IS NULL)
        OR (status = 'confirmed'
            AND confirmed_at IS NOT NULL AND cancelled_at IS NULL
            AND moved_in_at IS NULL AND resident_id IS NULL)
        OR (status = 'cancelled'
            AND cancelled_at IS NOT NULL AND moved_in_at IS NULL
            AND resident_id IS NULL)
        OR (status = 'moved_in'
            AND confirmed_at IS NOT NULL AND cancelled_at IS NULL
            AND moved_in_at IS NOT NULL AND resident_id IS NOT NULL)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS occupancies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    resident_id BIGINT UNSIGNED NOT NULL,
    room_id BIGINT UNSIGNED NOT NULL,
    booking_id BIGINT UNSIGNED NOT NULL,
    monthly_rent DECIMAL(12,2) NOT NULL,
    status ENUM('active', 'ended') NOT NULL DEFAULT 'active',
    move_in_date DATE NOT NULL,
    move_out_date DATE NULL,
    opening_water_reading DECIMAL(14,2) NULL,
    opening_electric_reading DECIMAL(14,2) NULL,
    active_room_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (CASE WHEN status = 'active' THEN room_id ELSE NULL END) STORED,
    active_resident_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (CASE WHEN status = 'active' THEN resident_id ELSE NULL END) STORED,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_occupancies_booking (booking_id),
    UNIQUE KEY uq_occupancies_one_active_per_room (active_room_id),
    UNIQUE KEY uq_occupancies_one_active_per_resident (active_resident_id),
    KEY idx_occupancies_room_history (room_id, move_in_date),
    KEY idx_occupancies_resident_history (resident_id, move_in_date),
    CONSTRAINT fk_occupancies_resident
        FOREIGN KEY (resident_id) REFERENCES residents(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_occupancies_room
        FOREIGN KEY (room_id) REFERENCES rooms(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_occupancies_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_occupancies_monthly_rent
        CHECK (monthly_rent > 0 AND monthly_rent <= 1000000),
    CONSTRAINT chk_occupancies_dates
        CHECK (move_out_date IS NULL OR move_out_date >= move_in_date),
    CONSTRAINT chk_occupancies_opening_readings CHECK (
        (
            status = 'ended'
            AND opening_water_reading IS NULL
            AND opening_electric_reading IS NULL
        )
        OR (
            opening_water_reading >= 0
            AND opening_water_reading <= 9999999.00
            AND opening_electric_reading >= 0
            AND opening_electric_reading <= 9999999.00
        )
    ),
    CONSTRAINT chk_occupancies_state
        CHECK ((status = 'active' AND move_out_date IS NULL)
            OR (status = 'ended' AND move_out_date IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meter_readings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    room_id BIGINT UNSIGNED NOT NULL,
    occupancy_id BIGINT UNSIGNED NULL,
    meter_type ENUM('water', 'electric') NOT NULL,
    period DATE NOT NULL,
    previous_reading DECIMAL(14,2) NOT NULL,
    current_reading DECIMAL(14,2) NOT NULL,
    units_used DECIMAL(14,2) NOT NULL,
    recorded_by BIGINT UNSIGNED NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_meter_readings_room_type_period (room_id, meter_type, period),
    KEY idx_meter_readings_period (period, room_id),
    KEY idx_meter_readings_occupancy_period (occupancy_id, period),
    CONSTRAINT fk_meter_readings_room
        FOREIGN KEY (room_id) REFERENCES rooms(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_meter_readings_occupancy
        FOREIGN KEY (occupancy_id) REFERENCES occupancies(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_meter_readings_recorded_by
        FOREIGN KEY (recorded_by) REFERENCES admin_users(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_meter_readings_period CHECK (DAY(period) = 1),
    CONSTRAINT chk_meter_readings_nonnegative
        CHECK (previous_reading >= 0 AND current_reading >= 0 AND units_used >= 0),
    CONSTRAINT chk_meter_readings_monotonic CHECK (current_reading >= previous_reading),
    CONSTRAINT chk_meter_readings_units
        CHECK (units_used = ROUND(current_reading - previous_reading, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_settings (
    id TINYINT UNSIGNED NOT NULL,
    water_rate DECIMAL(12,2) NOT NULL,
    electric_rate DECIMAL(12,2) NOT NULL,
    due_days TINYINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_billing_settings_updated_by
        FOREIGN KEY (updated_by) REFERENCES admin_users(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_billing_settings_singleton CHECK (id = 1),
    CONSTRAINT chk_billing_settings_water_rate
        CHECK (water_rate >= 0 AND water_rate <= 1000000),
    CONSTRAINT chk_billing_settings_electric_rate
        CHECK (electric_rate >= 0 AND electric_rate <= 1000000),
    CONSTRAINT chk_billing_settings_due_days CHECK (due_days BETWEEN 1 AND 60)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Operational integration settings are deliberately stored in MySQL so an
-- owner can rotate PromptPay, LINE and slip-verification configuration from
-- the admin console without changing source files or restarting containers.
-- Credential columns contain AES-256-GCM envelopes produced by SecretCipher;
-- APP_KEY remains an infrastructure secret because it is needed to decrypt
-- this table and therefore cannot itself be stored here.
CREATE TABLE IF NOT EXISTS integration_settings (
    id TINYINT UNSIGNED NOT NULL,
    promptpay_target VARCHAR(13) CHARACTER SET ascii COLLATE ascii_bin NULL,
    promptpay_name VARCHAR(120) NULL,
    payment_receiver_account_tail VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NULL,
    line_basic_id VARCHAR(33) CHARACTER SET ascii COLLATE ascii_bin NULL,
    line_channel_access_token_enc TEXT CHARACTER SET ascii COLLATE ascii_bin NULL,
    line_channel_secret_enc TEXT CHARACTER SET ascii COLLATE ascii_bin NULL,
    line_max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 5,
    notification_batch_size TINYINT UNSIGNED NOT NULL DEFAULT 25,
    slip_provider ENUM('none', 'slipok', 'easyslip') NOT NULL DEFAULT 'none',
    slipok_api_key_enc TEXT CHARACTER SET ascii COLLATE ascii_bin NULL,
    slipok_branch_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL,
    easyslip_api_key_enc TEXT CHARACTER SET ascii COLLATE ascii_bin NULL,
    slip_max_bytes INT UNSIGNED NOT NULL DEFAULT 4194304,
    slip_time_tolerance_seconds SMALLINT UNSIGNED NOT NULL DEFAULT 300,
    updated_by BIGINT UNSIGNED NULL,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_integration_settings_updated_by
        FOREIGN KEY (updated_by) REFERENCES admin_users(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_integration_settings_singleton CHECK (id = 1),
    CONSTRAINT chk_integration_settings_promptpay CHECK (
        promptpay_target IS NULL
        OR promptpay_target REGEXP '^(0[0-9]{9}|[0-9]{13})$'
    ),
    CONSTRAINT chk_integration_settings_promptpay_name CHECK (
        promptpay_name IS NULL
        OR CHAR_LENGTH(TRIM(promptpay_name)) BETWEEN 1 AND 120
    ),
    CONSTRAINT chk_integration_settings_receiver_tail CHECK (
        payment_receiver_account_tail IS NULL
        OR payment_receiver_account_tail REGEXP '^[0-9]{6,20}$'
    ),
    CONSTRAINT chk_integration_settings_line_basic_id CHECK (
        line_basic_id IS NULL
        OR line_basic_id REGEXP '^@[A-Za-z0-9._-]{1,32}$'
    ),
    CONSTRAINT chk_integration_settings_line_token CHECK (
        line_channel_access_token_enc IS NULL
        OR CHAR_LENGTH(line_channel_access_token_enc) BETWEEN 20 AND 65000
    ),
    CONSTRAINT chk_integration_settings_line_secret CHECK (
        line_channel_secret_enc IS NULL
        OR CHAR_LENGTH(line_channel_secret_enc) BETWEEN 20 AND 65000
    ),
    CONSTRAINT chk_integration_settings_line_attempts CHECK (line_max_attempts BETWEEN 1 AND 20),
    CONSTRAINT chk_integration_settings_batch CHECK (notification_batch_size BETWEEN 1 AND 100),
    CONSTRAINT chk_integration_settings_slipok_key CHECK (
        slipok_api_key_enc IS NULL
        OR CHAR_LENGTH(slipok_api_key_enc) BETWEEN 20 AND 65000
    ),
    CONSTRAINT chk_integration_settings_slipok_branch CHECK (
        slipok_branch_id IS NULL
        OR slipok_branch_id REGEXP '^[A-Za-z0-9_-]{1,80}$'
    ),
    CONSTRAINT chk_integration_settings_easyslip_key CHECK (
        easyslip_api_key_enc IS NULL
        OR CHAR_LENGTH(easyslip_api_key_enc) BETWEEN 20 AND 65000
    ),
    CONSTRAINT chk_integration_settings_slip_size CHECK (slip_max_bytes BETWEEN 1024 AND 4194304),
    CONSTRAINT chk_integration_settings_slip_time CHECK (slip_time_tolerance_seconds BETWEEN 0 AND 3600)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bills (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bill_no VARCHAR(50) NOT NULL,
    occupancy_id BIGINT UNSIGNED NOT NULL,
    resident_id BIGINT UNSIGNED NOT NULL,
    room_id BIGINT UNSIGNED NOT NULL,
    resident_name_snapshot VARCHAR(150) NOT NULL,
    room_code_snapshot VARCHAR(32) NOT NULL,
    period DATE NOT NULL,
    due_date DATE NOT NULL,
    rent_amount DECIMAL(14,2) NOT NULL,
    water_previous DECIMAL(14,2) NOT NULL,
    water_current DECIMAL(14,2) NOT NULL,
    water_units DECIMAL(14,2) NOT NULL,
    water_rate DECIMAL(12,2) NOT NULL,
    water_amount DECIMAL(14,2) NOT NULL,
    electric_previous DECIMAL(14,2) NOT NULL,
    electric_current DECIMAL(14,2) NOT NULL,
    electric_units DECIMAL(14,2) NOT NULL,
    electric_rate DECIMAL(12,2) NOT NULL,
    electric_amount DECIMAL(14,2) NOT NULL,
    other_description VARCHAR(255) NULL,
    other_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(14,2) NOT NULL,
    status ENUM('pending', 'paid') NOT NULL DEFAULT 'pending',
    paid_at DATETIME(6) NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_bills_bill_no (bill_no),
    UNIQUE KEY uq_bills_occupancy_period (occupancy_id, period),
    KEY idx_bills_resident_created (resident_id, created_at),
    KEY idx_bills_room_period (room_id, period),
    KEY idx_bills_status_due (status, due_date),
    CONSTRAINT fk_bills_occupancy
        FOREIGN KEY (occupancy_id) REFERENCES occupancies(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_bills_resident
        FOREIGN KEY (resident_id) REFERENCES residents(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_bills_room
        FOREIGN KEY (room_id) REFERENCES rooms(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_bills_created_by
        FOREIGN KEY (created_by) REFERENCES admin_users(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_bills_period CHECK (DAY(period) = 1),
    CONSTRAINT chk_bills_resident_name CHECK (CHAR_LENGTH(TRIM(resident_name_snapshot)) BETWEEN 1 AND 150),
    CONSTRAINT chk_bills_room_code CHECK (CHAR_LENGTH(TRIM(room_code_snapshot)) BETWEEN 1 AND 32),
    CONSTRAINT chk_bills_due_date CHECK (due_date >= period),
    CONSTRAINT chk_bills_nonnegative CHECK (
        rent_amount >= 0
        AND water_previous >= 0 AND water_current >= 0 AND water_units >= 0
        AND water_rate >= 0 AND water_amount >= 0
        AND electric_previous >= 0 AND electric_current >= 0 AND electric_units >= 0
        AND electric_rate >= 0 AND electric_amount >= 0
        AND other_amount >= 0 AND total_amount >= 0
    ),
    CONSTRAINT chk_bills_water_usage CHECK (
        water_current >= water_previous
        AND water_units = ROUND(water_current - water_previous, 2)
        AND water_amount = ROUND(water_units * water_rate, 2)
    ),
    CONSTRAINT chk_bills_electric_usage CHECK (
        electric_current >= electric_previous
        AND electric_units = ROUND(electric_current - electric_previous, 2)
        AND electric_amount = ROUND(electric_units * electric_rate, 2)
    ),
    CONSTRAINT chk_bills_other_description CHECK (
        (other_amount = 0 AND other_description IS NULL)
        OR (other_amount > 0
            AND other_description IS NOT NULL
            AND CHAR_LENGTH(TRIM(other_description)) BETWEEN 1 AND 255)
    ),
    CONSTRAINT chk_bills_total CHECK (
        total_amount = ROUND(
            rent_amount + water_amount + electric_amount + other_amount,
            2
        )
    ),
    CONSTRAINT chk_bills_paid_state CHECK (
        (status = 'paid' AND paid_at IS NOT NULL)
        OR (status = 'pending' AND paid_at IS NULL)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bill_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bill_id BIGINT UNSIGNED NOT NULL,
    item_type ENUM('rent', 'water', 'electric', 'other') NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity DECIMAL(14,2) NOT NULL,
    unit_price DECIMAL(14,2) NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bill_items_bill_type (bill_id, item_type),
    KEY idx_bill_items_bill (bill_id, id),
    CONSTRAINT fk_bill_items_bill
        FOREIGN KEY (bill_id) REFERENCES bills(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_bill_items_description CHECK (CHAR_LENGTH(TRIM(description)) BETWEEN 1 AND 255),
    CONSTRAINT chk_bill_items_amounts
        CHECK (quantity >= 0 AND unit_price >= 0 AND amount >= 0),
    CONSTRAINT chk_bill_items_math CHECK (amount = ROUND(quantity * unit_price, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bill_id BIGINT UNSIGNED NOT NULL,
    resident_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    status ENUM('pending', 'verified', 'rejected') NOT NULL DEFAULT 'pending',
    slip_path VARCHAR(500) NOT NULL,
    slip_mime ENUM('image/jpeg', 'image/png', 'image/webp') NOT NULL,
    slip_hmac CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider VARCHAR(32) NULL,
    transaction_ref VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    receiver_ref VARCHAR(191) NULL,
    provider_payload JSON NULL,
    rejection_reason VARCHAR(500) NULL,
    verified_at DATETIME(6) NULL,
    verification_lease_until DATETIME(6) NULL,
    verification_token CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    verification_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    active_bill_id BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN status IN ('pending', 'verified') THEN bill_id ELSE NULL END
        ) STORED,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_payments_slip_hmac (slip_hmac),
    UNIQUE KEY uq_payments_transaction_ref (transaction_ref),
    UNIQUE KEY uq_payments_one_active_per_bill (active_bill_id),
    KEY idx_payments_resident_created (resident_id, created_at),
    KEY idx_payments_status_created (status, created_at),
    CONSTRAINT fk_payments_bill
        FOREIGN KEY (bill_id) REFERENCES bills(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_payments_resident
        FOREIGN KEY (resident_id) REFERENCES residents(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_payments_amount CHECK (amount > 0),
    CONSTRAINT chk_payments_slip_hmac CHECK (slip_hmac REGEXP '^[0-9a-f]{64}$'),
    CONSTRAINT chk_payments_verification_attempts CHECK (verification_attempts <= 100),
    CONSTRAINT chk_payments_verification_lease CHECK (
        (verification_lease_until IS NULL AND verification_token IS NULL)
        OR (status = 'pending'
            AND verification_lease_until IS NOT NULL
            AND verification_token IS NOT NULL
            AND verification_token REGEXP '^[0-9a-f]{64}$')
    ),
    CONSTRAINT chk_payments_state CHECK (
        (status = 'verified'
            AND transaction_ref IS NOT NULL
            AND verified_at IS NOT NULL
            AND rejection_reason IS NULL)
        OR (status = 'rejected'
            AND verified_at IS NULL
            AND rejection_reason IS NOT NULL
            AND CHAR_LENGTH(TRIM(rejection_reason)) BETWEEN 1 AND 500)
        OR (status = 'pending'
            AND verified_at IS NULL
            AND transaction_ref IS NULL)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_outbox (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bill_id BIGINT UNSIGNED NOT NULL,
    resident_id BIGINT UNSIGNED NOT NULL,
    channel ENUM('line') NOT NULL DEFAULT 'line',
    purpose VARCHAR(32) NOT NULL DEFAULT 'bill_delivery',
    recipient VARCHAR(33) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    payload JSON NOT NULL,
    status ENUM('pending', 'processing', 'sent', 'failed') NOT NULL DEFAULT 'pending',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    retry_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    claim_token CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lease_until DATETIME(6) NULL,
    line_request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    line_accepted_request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    last_error VARCHAR(1000) NULL,
    sent_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_notification_outbox_bill_purpose (bill_id, purpose),
    UNIQUE KEY uq_notification_outbox_retry_key (retry_key),
    KEY idx_notification_outbox_due (status, next_attempt_at),
    KEY idx_notification_outbox_lease (status, lease_until),
    KEY idx_notification_outbox_resident (resident_id, created_at),
    CONSTRAINT fk_notification_outbox_bill
        FOREIGN KEY (bill_id) REFERENCES bills(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_notification_outbox_resident
        FOREIGN KEY (resident_id) REFERENCES residents(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_notification_outbox_purpose
        CHECK (CHAR_LENGTH(TRIM(purpose)) BETWEEN 1 AND 32),
    CONSTRAINT chk_notification_outbox_recipient
        CHECK (recipient REGEXP '^U[0-9a-f]{32}$'),
    CONSTRAINT chk_notification_outbox_retry_key
        CHECK (retry_key REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
    CONSTRAINT chk_notification_outbox_line_request_id
        CHECK (line_request_id IS NULL OR line_request_id REGEXP '^[!-~]{1,128}$'),
    CONSTRAINT chk_notification_outbox_line_accepted_request_id
        CHECK (line_accepted_request_id IS NULL OR line_accepted_request_id REGEXP '^[!-~]{1,128}$'),
    CONSTRAINT chk_notification_outbox_attempts CHECK (attempts <= 100),
    CONSTRAINT chk_notification_outbox_claim_lease CHECK (
        (
            status = 'processing'
            AND claim_token REGEXP '^[0-9a-f]{64}$'
            AND lease_until IS NOT NULL
        )
        OR (
            status <> 'processing'
            AND claim_token IS NULL
            AND lease_until IS NULL
        )
    ),
    CONSTRAINT chk_notification_outbox_sent CHECK (
        (status = 'sent' AND sent_at IS NOT NULL)
        OR (status <> 'sent' AND sent_at IS NULL)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_worker_heartbeats (
    worker_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status ENUM('starting', 'running', 'error', 'stopped') NOT NULL,
    started_at DATETIME(6) NOT NULL,
    heartbeat_at DATETIME(6) NOT NULL,
    last_cycle_at DATETIME(6) NULL,
    last_processed INT UNSIGNED NOT NULL DEFAULT 0,
    last_sent INT UNSIGNED NOT NULL DEFAULT 0,
    last_failed INT UNSIGNED NOT NULL DEFAULT 0,
    last_retried INT UNSIGNED NOT NULL DEFAULT 0,
    last_lost_claims INT UNSIGNED NOT NULL DEFAULT 0,
    last_recovered INT UNSIGNED NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (worker_id),
    KEY idx_notification_worker_heartbeat (heartbeat_at),
    CONSTRAINT chk_notification_worker_id
        CHECK (worker_id REGEXP '^[0-9a-f]{64}$'),
    CONSTRAINT chk_notification_worker_error CHECK (
        last_error IS NULL
        OR CHAR_LENGTH(TRIM(last_error)) BETWEEN 1 AND 1000
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    actor_type ENUM('admin', 'resident', 'guest', 'system') NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    action VARCHAR(120) NOT NULL,
    entity_type VARCHAR(64) NULL,
    entity_id VARCHAR(64) NULL,
    details JSON NULL,
    ip VARCHAR(45) NULL,
    user_agent VARCHAR(512) NULL,
    request_id VARCHAR(64) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_audit_logs_created (created_at),
    KEY idx_audit_logs_actor (actor_type, actor_id, created_at),
    KEY idx_audit_logs_entity (entity_type, entity_id, created_at),
    KEY idx_audit_logs_request (request_id),
    CONSTRAINT chk_audit_logs_action CHECK (CHAR_LENGTH(TRIM(action)) BETWEEN 1 AND 120)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rate_limits (
    bucket_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    window_started_at DATETIME(6) NOT NULL,
    hits INT UNSIGNED NOT NULL DEFAULT 0,
    blocked_until DATETIME(6) NULL,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (bucket_key),
    KEY idx_rate_limits_blocked (blocked_until),
    KEY idx_rate_limits_updated (updated_at),
    CONSTRAINT chk_rate_limits_hits CHECK (hits <= 1000000),
    CONSTRAINT chk_rate_limits_block_window CHECK (
        blocked_until IS NULL OR blocked_until >= window_started_at
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Fail before replacing any integrity trigger when an operator accidentally
-- runs the fresh bootstrap over a pre-002 database. CREATE TABLE IF NOT EXISTS
-- does not upgrade existing tables; the one-time migrations must do that. A
-- prepared read against a deliberately nonexistent information_schema table
-- aborts before any DROP TRIGGER and does not require CREATE ROUTINE/SUPER.
SET @dormitory_required_column_count := (
    SELECT COUNT(*)
      FROM information_schema.columns
     WHERE table_schema = DATABASE()
       AND (
            (table_name = 'bookings' AND column_name = 'booked_monthly_rent')
         OR (table_name = 'bills' AND column_name IN ('resident_name_snapshot', 'room_code_snapshot'))
         OR (table_name = 'payments' AND column_name IN ('verification_lease_until', 'verification_token', 'verification_attempts'))
       )
);
SET @dormitory_bill_item_index_columns := (
    SELECT COUNT(*)
      FROM information_schema.statistics
     WHERE table_schema = DATABASE()
       AND table_name = 'bill_items'
       AND index_name = 'uq_bill_items_bill_type'
       AND non_unique = 0
);
SET @dormitory_schema_guard_sql := IF(
    @dormitory_required_column_count = 6 AND @dormitory_bill_item_index_columns = 2,
    'SELECT 1',
    'SELECT * FROM information_schema.DORMITORY_ERROR_RUN_MIGRATION_002_FIRST'
);
PREPARE dormitory_schema_guard FROM @dormitory_schema_guard_sql;
EXECUTE dormitory_schema_guard;
DEALLOCATE PREPARE dormitory_schema_guard;

-- Financial snapshots and audit records are append-only. Bills may change only
-- their payment state; payment finalization updates status/paid_at atomically.
DROP TRIGGER IF EXISTS trg_bills_snapshot_immutable;
DROP TRIGGER IF EXISTS trg_bills_no_delete;
DROP TRIGGER IF EXISTS trg_bookings_identity_immutable;
DROP TRIGGER IF EXISTS trg_occupancies_identity_immutable;
DROP TRIGGER IF EXISTS trg_bill_items_insert_guard;
DROP TRIGGER IF EXISTS trg_bill_items_no_update;
DROP TRIGGER IF EXISTS trg_bill_items_no_delete;
DROP TRIGGER IF EXISTS trg_audit_logs_no_update;
DROP TRIGGER IF EXISTS trg_audit_logs_no_delete;
DROP TRIGGER IF EXISTS trg_payments_final_immutable;
DROP TRIGGER IF EXISTS trg_payments_no_delete;
DROP TRIGGER IF EXISTS trg_bills_relationship_guard;
DROP TRIGGER IF EXISTS trg_payments_relationship_guard;
DROP TRIGGER IF EXISTS trg_notification_relationship_guard;
DROP TRIGGER IF EXISTS trg_notification_relationship_guard_update;
DROP TRIGGER IF EXISTS trg_meter_readings_occupancy_guard;
DROP TRIGGER IF EXISTS trg_meter_readings_occupancy_guard_update;
DROP TRIGGER IF EXISTS trg_bookings_insert_guard;
DROP TRIGGER IF EXISTS trg_occupancies_relationship_guard;

DELIMITER $$

CREATE TRIGGER trg_bookings_insert_guard
BEFORE INSERT ON bookings
FOR EACH ROW
BEGIN
    DECLARE room_deleted DATETIME(6) DEFAULT NULL;
    DECLARE active_occupancy_count INT UNSIGNED DEFAULT 0;
    DECLARE active_phone_occupancy_count INT UNSIGNED DEFAULT 0;

    SELECT deleted_at
      INTO room_deleted
      FROM rooms
     WHERE id = NEW.room_id
     LIMIT 1
     FOR UPDATE;
    SELECT COUNT(*)
      INTO active_occupancy_count
      FROM occupancies
     WHERE room_id = NEW.room_id
       AND status = 'active'
     FOR SHARE;
    SELECT COUNT(*)
      INTO active_phone_occupancy_count
      FROM residents resident_row
      JOIN occupancies active_occupancy
        ON active_occupancy.resident_id = resident_row.id
       AND active_occupancy.status = 'active'
     WHERE resident_row.phone_norm = NEW.phone_norm
     FOR SHARE;

    IF NEW.status <> 'pending'
        OR room_deleted IS NOT NULL
        OR active_occupancy_count <> 0
        OR active_phone_occupancy_count <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A booking must start pending for an available room and resident';
    END IF;
END$$

CREATE TRIGGER trg_bookings_identity_immutable
BEFORE UPDATE ON bookings
FOR EACH ROW
BEGIN
    IF NOT (OLD.reference_no <=> NEW.reference_no)
        OR NOT (OLD.room_id <=> NEW.room_id)
        OR NOT (OLD.full_name <=> NEW.full_name)
        OR NOT (OLD.phone_norm <=> NEW.phone_norm)
        OR NOT (OLD.booked_monthly_rent <=> NEW.booked_monthly_rent)
        OR NOT (OLD.idempotency_key <=> NEW.idempotency_key)
        OR NOT (OLD.created_at <=> NEW.created_at) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Booking identity and rent snapshot are immutable';
    END IF;
    IF NOT (
        OLD.status = NEW.status
        OR (OLD.status = 'pending' AND NEW.status IN ('confirmed', 'cancelled'))
        OR (OLD.status = 'confirmed' AND NEW.status IN ('cancelled', 'moved_in'))
    ) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Invalid booking state transition';
    END IF;
    IF (OLD.confirmed_at IS NOT NULL
            AND (NOT (OLD.confirmed_at <=> NEW.confirmed_at)
                OR NOT (OLD.confirmed_by <=> NEW.confirmed_by)))
        OR (OLD.cancelled_at IS NOT NULL
            AND (NOT (OLD.cancelled_at <=> NEW.cancelled_at)
                OR NOT (OLD.cancelled_by <=> NEW.cancelled_by)
                OR NOT (OLD.cancel_reason <=> NEW.cancel_reason)))
        OR (OLD.moved_in_at IS NOT NULL
            AND (NOT (OLD.moved_in_at <=> NEW.moved_in_at)
                OR NOT (OLD.resident_id <=> NEW.resident_id)))
        OR (OLD.status = 'moved_in'
            AND NOT (OLD.move_in_request_hash <=> NEW.move_in_request_hash)) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Booking transition evidence is immutable once recorded';
    END IF;
END$$

-- A string local declared without CHARACTER SET inherits the DATABASE default
-- collation, not the collation of the tables it is compared against, so the
-- declarations below pin it explicitly. See trg_bill_items_insert_guard.
CREATE TRIGGER trg_occupancies_relationship_guard
BEFORE INSERT ON occupancies
FOR EACH ROW
BEGIN
    DECLARE booking_status VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;
    DECLARE booking_resident BIGINT UNSIGNED DEFAULT NULL;
    DECLARE booking_room BIGINT UNSIGNED DEFAULT NULL;
    DECLARE booking_rent DECIMAL(12,2) DEFAULT NULL;
    DECLARE resident_active TINYINT DEFAULT NULL;
    DECLARE room_deleted DATETIME(6) DEFAULT NULL;
    DECLARE overlapping_periods INT UNSIGNED DEFAULT 0;

    SELECT deleted_at
      INTO room_deleted
      FROM rooms
     WHERE id = NEW.room_id
     LIMIT 1
     FOR UPDATE;
    SELECT active
      INTO resident_active
      FROM residents
     WHERE id = NEW.resident_id
     LIMIT 1
     FOR UPDATE;
    SELECT status, resident_id, room_id, booked_monthly_rent
      INTO booking_status, booking_resident, booking_room, booking_rent
      FROM bookings
     WHERE id = NEW.booking_id
     LIMIT 1
     FOR SHARE;
    SELECT COUNT(*)
      INTO overlapping_periods
      FROM occupancies existing_occupancy
     WHERE (
            existing_occupancy.room_id = NEW.room_id
            OR existing_occupancy.resident_id = NEW.resident_id
       )
       AND DATE_FORMAT(existing_occupancy.move_in_date, '%Y-%m-01')
               <= DATE_FORMAT(COALESCE(NEW.move_out_date, '9999-12-31'), '%Y-%m-01')
       AND DATE_FORMAT(NEW.move_in_date, '%Y-%m-01')
               <= DATE_FORMAT(
                   COALESCE(existing_occupancy.move_out_date, '9999-12-31'),
                   '%Y-%m-01'
               )
     FOR SHARE;

    IF NEW.status <> 'active'
        OR NEW.move_out_date IS NOT NULL
        OR NEW.opening_water_reading IS NULL
        OR NEW.opening_electric_reading IS NULL
        OR room_deleted IS NOT NULL
        OR resident_active <> 1
        OR booking_status <> 'moved_in'
        OR NOT (booking_resident <=> NEW.resident_id)
        OR NOT (booking_room <=> NEW.room_id)
        OR NOT (booking_rent <=> NEW.monthly_rent)
        OR overlapping_periods <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Occupancy must start active and match its moved-in booking';
    END IF;
END$$

CREATE TRIGGER trg_occupancies_identity_immutable
BEFORE UPDATE ON occupancies
FOR EACH ROW
BEGIN
    IF NOT (OLD.resident_id <=> NEW.resident_id)
        OR NOT (OLD.room_id <=> NEW.room_id)
        OR NOT (OLD.booking_id <=> NEW.booking_id)
        OR NOT (OLD.monthly_rent <=> NEW.monthly_rent)
        OR NOT (OLD.move_in_date <=> NEW.move_in_date)
        OR NOT (OLD.opening_water_reading <=> NEW.opening_water_reading)
        OR NOT (OLD.opening_electric_reading <=> NEW.opening_electric_reading)
        OR NOT (OLD.created_at <=> NEW.created_at) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Occupancy identity and rent snapshot are immutable';
    END IF;
    IF OLD.status = 'ended'
        AND (NEW.status <> 'ended' OR NOT (OLD.move_out_date <=> NEW.move_out_date)) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'An ended occupancy is immutable';
    END IF;
    IF OLD.status = 'active' AND NEW.status NOT IN ('active', 'ended') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Invalid occupancy state transition';
    END IF;
END$$

CREATE TRIGGER trg_meter_readings_occupancy_guard
BEFORE INSERT ON meter_readings
FOR EACH ROW
BEGIN
    DECLARE occupancy_room BIGINT UNSIGNED DEFAULT NULL;
    DECLARE occupancy_move_in DATE DEFAULT NULL;
    DECLARE occupancy_move_out DATE DEFAULT NULL;
    DECLARE occupancy_opening_water DECIMAL(14,2) DEFAULT NULL;
    DECLARE occupancy_opening_electric DECIMAL(14,2) DEFAULT NULL;
    DECLARE expected_previous DECIMAL(14,2) DEFAULT NULL;
    DECLARE prior_rows INT UNSIGNED DEFAULT 0;
    DECLARE overlapping_occupancies INT UNSIGNED DEFAULT 0;

    IF NEW.occupancy_id IS NULL THEN
        SELECT COUNT(*) INTO overlapping_occupancies
          FROM occupancies
         WHERE room_id = NEW.room_id
           AND move_in_date <= LAST_DAY(NEW.period)
           AND (move_out_date IS NULL OR move_out_date >= NEW.period);
        IF overlapping_occupancies <> 0 THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'An occupied-room meter reading requires occupancy_id';
        END IF;
    ELSE
        SELECT room_id, move_in_date, move_out_date,
               opening_water_reading, opening_electric_reading
          INTO occupancy_room, occupancy_move_in, occupancy_move_out,
               occupancy_opening_water, occupancy_opening_electric
          FROM occupancies
         WHERE id = NEW.occupancy_id
         LIMIT 1;
        IF NOT (occupancy_room <=> NEW.room_id)
            OR occupancy_move_in > LAST_DAY(NEW.period)
            OR (occupancy_move_out IS NOT NULL
                AND occupancy_move_out < NEW.period) THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Meter reading must belong to its occupancy period and room';
        END IF;
        IF DATE_FORMAT(occupancy_move_in, '%Y-%m-01') = NEW.period THEN
            SET expected_previous = IF(
                NEW.meter_type = 'water',
                occupancy_opening_water,
                occupancy_opening_electric
            );
            IF expected_previous IS NULL
                OR NOT (expected_previous <=> NEW.previous_reading) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'First-period meter baseline must match the occupancy opening reading';
            END IF;
        ELSE
            SELECT COUNT(*), MAX(current_reading)
              INTO prior_rows, expected_previous
              FROM meter_readings
             WHERE room_id = NEW.room_id
               AND occupancy_id = NEW.occupancy_id
               AND meter_type = NEW.meter_type
               AND period = DATE_SUB(NEW.period, INTERVAL 1 MONTH);
            IF prior_rows <> 1
                OR NOT (expected_previous <=> NEW.previous_reading) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Meter history must be contiguous within one occupancy';
            END IF;
        END IF;
    END IF;
END$$

CREATE TRIGGER trg_meter_readings_occupancy_guard_update
BEFORE UPDATE ON meter_readings
FOR EACH ROW
BEGIN
    DECLARE occupancy_room BIGINT UNSIGNED DEFAULT NULL;
    DECLARE occupancy_move_in DATE DEFAULT NULL;
    DECLARE occupancy_move_out DATE DEFAULT NULL;
    DECLARE occupancy_opening_water DECIMAL(14,2) DEFAULT NULL;
    DECLARE occupancy_opening_electric DECIMAL(14,2) DEFAULT NULL;
    DECLARE expected_previous DECIMAL(14,2) DEFAULT NULL;
    DECLARE prior_rows INT UNSIGNED DEFAULT 0;
    DECLARE later_rows INT UNSIGNED DEFAULT 0;
    DECLARE overlapping_occupancies INT UNSIGNED DEFAULT 0;

    IF NOT (OLD.room_id <=> NEW.room_id)
        OR NOT (OLD.meter_type <=> NEW.meter_type)
        OR NOT (OLD.period <=> NEW.period)
        OR NOT (OLD.previous_reading <=> NEW.previous_reading)
        OR NOT (OLD.created_at <=> NEW.created_at)
        OR (OLD.occupancy_id IS NOT NULL
            AND NOT (OLD.occupancy_id <=> NEW.occupancy_id)) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Meter identity and previous reading are immutable';
    END IF;

    IF NEW.occupancy_id IS NULL THEN
        SELECT COUNT(*) INTO overlapping_occupancies
          FROM occupancies
         WHERE room_id = NEW.room_id
           AND move_in_date <= LAST_DAY(NEW.period)
           AND (move_out_date IS NULL OR move_out_date >= NEW.period);
        IF overlapping_occupancies <> 0 THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'An occupied-room meter reading requires occupancy_id';
        END IF;
    ELSE
        SELECT room_id, move_in_date, move_out_date,
               opening_water_reading, opening_electric_reading
          INTO occupancy_room, occupancy_move_in, occupancy_move_out,
               occupancy_opening_water, occupancy_opening_electric
          FROM occupancies
         WHERE id = NEW.occupancy_id
         LIMIT 1;
        IF NOT (occupancy_room <=> NEW.room_id)
            OR occupancy_move_in > LAST_DAY(NEW.period)
            OR (occupancy_move_out IS NOT NULL
                AND occupancy_move_out < NEW.period) THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Meter reading must belong to its occupancy period and room';
        END IF;
        IF DATE_FORMAT(occupancy_move_in, '%Y-%m-01') = NEW.period THEN
            SET expected_previous = IF(
                NEW.meter_type = 'water',
                occupancy_opening_water,
                occupancy_opening_electric
            );
            IF expected_previous IS NULL
                OR NOT (expected_previous <=> NEW.previous_reading) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'First-period meter baseline must match the occupancy opening reading';
            END IF;
        ELSE
            SELECT COUNT(*), MAX(current_reading)
              INTO prior_rows, expected_previous
              FROM meter_readings
             WHERE room_id = NEW.room_id
               AND occupancy_id = NEW.occupancy_id
               AND meter_type = NEW.meter_type
               AND period = DATE_SUB(NEW.period, INTERVAL 1 MONTH);
            IF prior_rows <> 1
                OR NOT (expected_previous <=> NEW.previous_reading) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Meter history must be contiguous within one occupancy';
            END IF;
        END IF;
        IF NOT (OLD.current_reading <=> NEW.current_reading) THEN
            SELECT COUNT(*) INTO later_rows
              FROM meter_readings
             WHERE room_id = NEW.room_id
               AND meter_type = NEW.meter_type
               AND period > NEW.period;
            IF later_rows <> 0 THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'A meter reading referenced by a later period is immutable';
            END IF;
        END IF;
    END IF;
END$$

CREATE TRIGGER trg_bills_snapshot_immutable
BEFORE UPDATE ON bills
FOR EACH ROW
BEGIN
    DECLARE verified_payment_count INT UNSIGNED DEFAULT 0;
    IF NOT (OLD.bill_no <=> NEW.bill_no)
        OR NOT (OLD.occupancy_id <=> NEW.occupancy_id)
        OR NOT (OLD.resident_id <=> NEW.resident_id)
        OR NOT (OLD.room_id <=> NEW.room_id)
        OR NOT (OLD.resident_name_snapshot <=> NEW.resident_name_snapshot)
        OR NOT (OLD.room_code_snapshot <=> NEW.room_code_snapshot)
        OR NOT (OLD.period <=> NEW.period)
        OR NOT (OLD.due_date <=> NEW.due_date)
        OR NOT (OLD.rent_amount <=> NEW.rent_amount)
        OR NOT (OLD.water_previous <=> NEW.water_previous)
        OR NOT (OLD.water_current <=> NEW.water_current)
        OR NOT (OLD.water_units <=> NEW.water_units)
        OR NOT (OLD.water_rate <=> NEW.water_rate)
        OR NOT (OLD.water_amount <=> NEW.water_amount)
        OR NOT (OLD.electric_previous <=> NEW.electric_previous)
        OR NOT (OLD.electric_current <=> NEW.electric_current)
        OR NOT (OLD.electric_units <=> NEW.electric_units)
        OR NOT (OLD.electric_rate <=> NEW.electric_rate)
        OR NOT (OLD.electric_amount <=> NEW.electric_amount)
        OR NOT (OLD.other_description <=> NEW.other_description)
        OR NOT (OLD.other_amount <=> NEW.other_amount)
        OR NOT (OLD.total_amount <=> NEW.total_amount)
        OR NOT (OLD.created_by <=> NEW.created_by)
        OR NOT (OLD.created_at <=> NEW.created_at) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Bill financial snapshots are immutable';
    END IF;
    IF OLD.status = 'paid'
        AND (NEW.status <> 'paid' OR NOT (OLD.paid_at <=> NEW.paid_at)) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A paid bill cannot be reopened or re-timestamped';
    END IF;
    IF OLD.status = 'pending' AND NEW.status = 'paid' THEN
        SELECT COUNT(*) INTO verified_payment_count
          FROM payments
         WHERE bill_id = OLD.id
           AND status = 'verified'
           AND amount = OLD.total_amount;
        IF verified_payment_count <> 1 THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'A bill requires one matching verified payment';
        END IF;
    END IF;
END$$

CREATE TRIGGER trg_bills_relationship_guard
BEFORE INSERT ON bills
FOR EACH ROW
BEGIN
    DECLARE occupancy_resident BIGINT UNSIGNED DEFAULT NULL;
    DECLARE occupancy_room BIGINT UNSIGNED DEFAULT NULL;
    DECLARE occupancy_rent DECIMAL(12,2) DEFAULT NULL;
    DECLARE occupancy_move_in DATE DEFAULT NULL;
    DECLARE occupancy_move_out DATE DEFAULT NULL;
    DECLARE water_previous DECIMAL(14,2) DEFAULT NULL;
    DECLARE water_current DECIMAL(14,2) DEFAULT NULL;
    DECLARE water_units DECIMAL(14,2) DEFAULT NULL;
    DECLARE electric_previous DECIMAL(14,2) DEFAULT NULL;
    DECLARE electric_current DECIMAL(14,2) DEFAULT NULL;
    DECLARE electric_units DECIMAL(14,2) DEFAULT NULL;

    SELECT resident_id, room_id, monthly_rent, move_in_date, move_out_date
      INTO occupancy_resident, occupancy_room, occupancy_rent,
           occupancy_move_in, occupancy_move_out
      FROM occupancies
     WHERE id = NEW.occupancy_id
     LIMIT 1
     FOR SHARE;
    SELECT previous_reading, current_reading, units_used
      INTO water_previous, water_current, water_units
      FROM meter_readings
     WHERE room_id = NEW.room_id
       AND occupancy_id = NEW.occupancy_id
       AND meter_type = 'water'
       AND period = NEW.period
     LIMIT 1
     FOR SHARE;
    SELECT previous_reading, current_reading, units_used
      INTO electric_previous, electric_current, electric_units
      FROM meter_readings
     WHERE room_id = NEW.room_id
       AND occupancy_id = NEW.occupancy_id
       AND meter_type = 'electric'
       AND period = NEW.period
     LIMIT 1
     FOR SHARE;

    IF NEW.status <> 'pending'
        OR NEW.paid_at IS NOT NULL
        OR NOT (occupancy_resident <=> NEW.resident_id)
        OR NOT (occupancy_room <=> NEW.room_id) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Bill must start pending and match its occupancy';
    END IF;
    IF NOT (occupancy_rent <=> NEW.rent_amount)
        OR NEW.period < DATE_FORMAT(occupancy_move_in, '%Y-%m-01')
        OR NEW.period > DATE_FORMAT(COALESCE(occupancy_move_out, '9999-12-31'), '%Y-%m-01')
        OR NOT (water_previous <=> NEW.water_previous)
        OR NOT (water_current <=> NEW.water_current)
        OR NOT (water_units <=> NEW.water_units)
        OR NOT (electric_previous <=> NEW.electric_previous)
        OR NOT (electric_current <=> NEW.electric_current)
        OR NOT (electric_units <=> NEW.electric_units) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Bill rent and meter snapshots must match its occupancy period';
    END IF;
END$$

CREATE TRIGGER trg_bills_no_delete
BEFORE DELETE ON bills
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Issued bills cannot be deleted';
END$$

-- expected_other_description is compared with bill_items.description using <=>.
-- Both operands are IMPLICIT, so different collations raise error 1267 and every
-- bill item insert fails. The database is utf8mb4_unicode_ci only when created by
-- database/install.sql; a managed host or MYSQL_DATABASE gives it the server
-- default, so the declaration pins the collation rather than inheriting it.
CREATE TRIGGER trg_bill_items_insert_guard
BEFORE INSERT ON bill_items
FOR EACH ROW
BEGIN
    DECLARE expected_quantity DECIMAL(14,2) DEFAULT NULL;
    DECLARE expected_unit_price DECIMAL(14,2) DEFAULT NULL;
    DECLARE expected_amount DECIMAL(14,2) DEFAULT NULL;
    DECLARE expected_other_description VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;

    SELECT CASE NEW.item_type
               WHEN 'rent' THEN 1.00
               WHEN 'water' THEN water_units
               WHEN 'electric' THEN electric_units
               WHEN 'other' THEN 1.00
           END,
           CASE NEW.item_type
               WHEN 'rent' THEN rent_amount
               WHEN 'water' THEN water_rate
               WHEN 'electric' THEN electric_rate
               WHEN 'other' THEN other_amount
           END,
           CASE NEW.item_type
               WHEN 'rent' THEN rent_amount
               WHEN 'water' THEN water_amount
               WHEN 'electric' THEN electric_amount
               WHEN 'other' THEN other_amount
           END,
           other_description
      INTO expected_quantity, expected_unit_price, expected_amount, expected_other_description
      FROM bills
     WHERE id = NEW.bill_id
     LIMIT 1;

    IF NOT (expected_quantity <=> NEW.quantity)
        OR NOT (expected_unit_price <=> NEW.unit_price)
        OR NOT (expected_amount <=> NEW.amount)
        OR (NEW.item_type = 'other'
            AND (expected_amount <= 0 OR NOT (expected_other_description <=> NEW.description))) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Bill item must match its issued bill snapshot';
    END IF;
END$$

CREATE TRIGGER trg_bill_items_no_update
BEFORE UPDATE ON bill_items
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Bill items are immutable';
END$$

CREATE TRIGGER trg_bill_items_no_delete
BEFORE DELETE ON bill_items
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Bill items are immutable';
END$$

-- The string local pins its collation for the same reason as the guards above.
CREATE TRIGGER trg_payments_relationship_guard
BEFORE INSERT ON payments
FOR EACH ROW
BEGIN
    DECLARE bill_resident BIGINT UNSIGNED DEFAULT NULL;
    DECLARE bill_total DECIMAL(14,2) DEFAULT NULL;
    DECLARE bill_status VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;
    SELECT resident_id, total_amount, status
      INTO bill_resident, bill_total, bill_status
      FROM bills
     WHERE id = NEW.bill_id
     LIMIT 1;
    IF NOT (bill_resident <=> NEW.resident_id)
        OR NOT (bill_total <=> NEW.amount)
        OR bill_status <> 'pending'
        OR NEW.status <> 'pending' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Payment must start pending and match a pending bill';
    END IF;
END$$

CREATE TRIGGER trg_payments_final_immutable
BEFORE UPDATE ON payments
FOR EACH ROW
BEGIN
    IF NOT (OLD.bill_id <=> NEW.bill_id)
        OR NOT (OLD.resident_id <=> NEW.resident_id)
        OR NOT (OLD.amount <=> NEW.amount)
        OR NOT (OLD.slip_path <=> NEW.slip_path)
        OR NOT (OLD.slip_mime <=> NEW.slip_mime)
        OR NOT (OLD.slip_hmac <=> NEW.slip_hmac)
        OR NOT (OLD.created_at <=> NEW.created_at) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Payment evidence identity is immutable';
    END IF;
    IF OLD.status IN ('verified', 'rejected')
        AND (NOT (OLD.status <=> NEW.status)
            OR NOT (OLD.provider <=> NEW.provider)
            OR NOT (OLD.transaction_ref <=> NEW.transaction_ref)
            OR NOT (OLD.receiver_ref <=> NEW.receiver_ref)
            OR NOT (OLD.provider_payload <=> NEW.provider_payload)
            OR NOT (OLD.rejection_reason <=> NEW.rejection_reason)
            OR NOT (OLD.verified_at <=> NEW.verified_at)
            OR NOT (OLD.verification_lease_until <=> NEW.verification_lease_until)
            OR NOT (OLD.verification_token <=> NEW.verification_token)
            OR NOT (OLD.verification_attempts <=> NEW.verification_attempts)) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A final payment decision is immutable';
    END IF;
END$$

CREATE TRIGGER trg_payments_no_delete
BEFORE DELETE ON payments
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Payment evidence cannot be deleted';
END$$

CREATE TRIGGER trg_notification_relationship_guard
BEFORE INSERT ON notification_outbox
FOR EACH ROW
BEGIN
    DECLARE bill_resident BIGINT UNSIGNED DEFAULT NULL;
    SELECT resident_id
      INTO bill_resident
      FROM bills
     WHERE id = NEW.bill_id
     LIMIT 1;
    IF NOT (bill_resident <=> NEW.resident_id) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Notification resident must match its bill';
    END IF;
END$$

CREATE TRIGGER trg_notification_relationship_guard_update
BEFORE UPDATE ON notification_outbox
FOR EACH ROW
BEGIN
    DECLARE bill_resident BIGINT UNSIGNED DEFAULT NULL;
    SELECT resident_id
      INTO bill_resident
      FROM bills
     WHERE id = NEW.bill_id
     LIMIT 1;
    IF NOT (OLD.bill_id <=> NEW.bill_id)
        OR NOT (bill_resident <=> NEW.resident_id) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Notification resident must match its immutable bill';
    END IF;
END$$

CREATE TRIGGER trg_audit_logs_no_update
BEFORE UPDATE ON audit_logs
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Audit logs are append-only';
END$$

CREATE TRIGGER trg_audit_logs_no_delete
BEFORE DELETE ON audit_logs
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Audit logs are append-only';
END$$

DELIMITER ;
-- END database/schema.sql

-- BEGIN database/defaults.sql
-- Required, idempotent baseline for a new deployment.
-- Safe for production: no room, resident, booking, bill, payment, admin,
-- password, PromptPay number, LINE token or slip-provider credential.
--
-- Water/electric rates intentionally start at zero and updated_by stays NULL.
-- An administrator must review and save the real billing settings before
-- issuing the first bill.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET time_zone = '+00:00';

INSERT IGNORE INTO billing_settings
    (id, water_rate, electric_rate, due_days, updated_by)
VALUES
    (1, 0.00, 0.00, 7, NULL);

-- Operational credentials start empty and are configured by an owner at
-- Admin -> Settings. No integration secret is stored in source control.
INSERT IGNORE INTO integration_settings
    (id, line_max_attempts, notification_batch_size, slip_provider,
     slip_max_bytes, slip_time_tolerance_seconds, updated_by)
VALUES
    (1, 5, 25, 'none', 4194304, 300, NULL);
-- END database/defaults.sql
