<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$root = dirname(__DIR__);
$target = $root . '/database/install.sql';
$sources = [
    'database/00-create-database.sql',
    'database/schema.sql',
    'database/defaults.sql',
];

$sections = [];
$sourceHashes = [];
foreach ($sources as $relative) {
    $path = $root . '/' . $relative;
    $sql = file_get_contents($path);
    if (!is_string($sql)) {
        fwrite(STDERR, "Cannot read {$relative}" . PHP_EOL);
        exit(1);
    }
    $sql = rtrim(str_replace(["\r\n", "\r"], "\n", $sql)) . "\n";
    $sourceHashes[] = $relative . ':' . hash('sha256', $sql);
    $sections[] = "-- BEGIN {$relative}\n{$sql}-- END {$relative}\n";
}

$freshDatabaseGuard = <<<'SQL'
-- BEGIN generated fresh-database guard
-- Refuse to touch an existing/partial database before schema.sql can create,
-- replace, or drop any object. Do not import this bundle with a force/continue
-- option; use database/migrations for an installed system instead.
SET @dormitory_existing_object_count := (
    SELECT COUNT(*)
      FROM information_schema.tables
     WHERE table_schema = DATABASE()
);
SET @dormitory_fresh_install_guard_sql := IF(
    DATABASE() = 'dormitory'
        AND @dormitory_existing_object_count = 0,
    'SELECT 1',
    'SELECT * FROM information_schema.DORMITORY_INSTALL_ABORT_DATABASE_NOT_EMPTY'
);
PREPARE dormitory_fresh_install_guard FROM @dormitory_fresh_install_guard_sql;
EXECUTE dormitory_fresh_install_guard;
DEALLOCATE PREPARE dormitory_fresh_install_guard;
-- END generated fresh-database guard
SQL;
array_splice($sections, 1, 0, [$freshDatabaseGuard . "\n"]);
$sourceHashes[] = 'generated-fresh-database-guard:' . hash('sha256', $freshDatabaseGuard . "\n");

$sourceDigest = hash('sha256', implode("\n", $sourceHashes));
$content = <<<SQL
-- AUTO-GENERATED FRESH-INSTALL BUNDLE. DO NOT EDIT THIS FILE DIRECTLY.
-- Import this one file from phpMyAdmin's server-level Import tab.
-- It creates/uses the `dormitory` database, current schema, triggers, and
-- safe baseline settings. It contains no owner, room, resident, demo data,
-- PromptPay number, LINE channel credential, or slip-provider credential.
-- Fresh installations only: it stops before changing a non-empty database.
-- Never use a force/continue-on-error import option with this file.
-- Regenerate: php scripts/build_install_sql.php
-- Verify current: php scripts/build_install_sql.php --check
-- Source digest: {$sourceDigest}

SQL;
$content .= implode("\n", $sections);

$checkOnly = in_array('--check', array_slice($argv, 1), true);
if ($checkOnly) {
    $current = file_get_contents($target);
    if (!is_string($current) || !hash_equals($content, str_replace(["\r\n", "\r"], "\n", $current))) {
        fwrite(STDERR, "database/install.sql is missing or out of date" . PHP_EOL);
        exit(1);
    }
    fwrite(STDOUT, "database/install.sql is current ({$sourceDigest})" . PHP_EOL);
    exit(0);
}

$temporary = $target . '.tmp-' . bin2hex(random_bytes(6));
if (file_put_contents($temporary, $content, LOCK_EX) !== strlen($content)) {
    @unlink($temporary);
    fwrite(STDERR, 'Unable to write temporary install SQL' . PHP_EOL);
    exit(1);
}
if (!rename($temporary, $target)) {
    @unlink($temporary);
    fwrite(STDERR, 'Unable to replace database/install.sql' . PHP_EOL);
    exit(1);
}

fwrite(STDOUT, "Generated database/install.sql ({$sourceDigest})" . PHP_EOL);
